id,Text,created_at,Emotion
401404767,"I wonder if we could just import this from xmlrpclib/xmlrpc.client instead? xmlrpclib should be stdlib, but I know some distros like to make things complicated. done.",2018-06-29T16:23:36Z,neutral
401413607,The test ansibletest sanity test import python 2.6 [[explain]( failed with 2 errors: lib/ansible/modules/net_tools/basics/get_url.py0: ImportError: cannot import name GzipDecodedResponse lib/ansible/modules/net_tools/basics/uri.py0: ImportError: cannot import name GzipDecodedResponse <! job_id: 5b365f611afbf70800aa34ab <! job_id: 5b365f67d77d9e080074b184 <! job_id: /testresults/ansibletestsanityimportpython2.6.json [click here for bot help]( <! boilerplate: shippable_test_result,2018-06-29T16:57:27Z,fear
401415066,Guess there is my answer. py2.6 does not have GzipDecodedResponse.,2018-06-29T17:02:54Z,neutral
409474751,"This could potentially fix bcoca: no, totally unrelated",2018-08-01T07:16:20Z,neutral
422057432,"I think I probably also need to create a custom HTTPError also, that adds some of the conveniences too.",2018-09-17T15:16:20Z,neutral
573856462,Bump. Adding this will make it so that ansible and by proxy ansible tower are capable of handling a situation where a device goes offline during the execution of a playbook. bcoca: it would not really change it as the tasks would still fail to initiate,2020-01-13T20:32:00Z,fear
623928981,This PR was evaluated as a potentially problematic PR for the following reasons: More than 50 changed files. Such PR can only be merged by human. Contact a Core team member to review this PR on IRC: devel on irc.freenode.net [click here for bot help]( <! boilerplate: bad_pr,2020-05-05T08:36:32Z,fear
623928985,": Greetings! Thanks for taking the time to open this pullrequest. In order for the community to handle your pullrequest effectively, we need a bit more information. Here are the items we could not find in your description: issue type Please set the description of this pullrequest with this template: [click here for bot help]( <! boilerplate: issue_missing_data ",2020-05-05T08:36:33Z,joy
656881018,Another option is creating a regex: true/false. Overloading the regexp field to accept a string and a boolean is far too confusing and wouldn't pass argument spec validation. I would definitely say no to that. I would suggest a new field rather than a toggle that changes the behavior of an existing field. Maybe raw_line or literal_line to indicate it is a literal string and will not be treated as a regexp pattern.,2020-07-10T20:42:52Z,neutral
677498123,+1 on this.,2020-08-20T09:50:19Z,neutral
700094143," It would simplify using Yubikey pkcs11, but wouldn't solve your issue.",2020-09-28T15:33:22Z,neutral
724606956,Would be great to have this feature.,2020-11-10T10:17:23Z,joy
738244000,Related to and .,2020-12-03T19:29:51Z,neutral
745434700,"+1 It would be nice, if the following could be made possible: yml name: <some_task_name shell: ""touch /tmp/some_file1 && touch /tmp/some_file2"" args: creates: ""/tmp/some_file1"" ""/tmp/some_file2"" The yml list should be an ORlink as default. Currently I have no clue how to indicate, that the list should be an ANDlink.",2020-12-15T17:13:26Z,joy
751393135,Related to and . you put the same issue twice :),2020-12-26T20:29:33Z,anger
754557306,I use antsibulldocs these days :woman_shrugging:,2021-01-05T10:43:07Z,neutral
754574759,"I would prefer to have only oVirt, but since there was a RHV before this is probably the best way...LGTM",2021-01-05T11:19:05Z,neutral
754599763,What is antsibulldocs?,2021-01-05T12:14:58Z,neutral
754685786,"closing as per reasoning in , this should be added to a collection.",2021-01-05T14:56:29Z,anger
754698251,closing as per above,2021-01-05T15:15:09Z,neutral
754701945,Unsure this belongs in ansible repo as this is not a requirement for collections in general nor community collections. cc,2021-01-05T15:20:56Z,fear
754703403,"Heh. Thanks, this was to ram in an invite to the docs survey, which has now expired. I'll remove the extra header.",2021-01-05T15:23:24Z,joy
754706936," ack, but the way we do certification testing is through ansibletest which seems like the right place to hold that test, until we split the testing upstream and downstream.",2021-01-05T15:28:43Z,fear
754708274,closing as per above,2021-01-05T15:30:45Z,neutral
754713679," As there is no separate collection for ansible.builtin modules, staying up to date with ansiblecore is unfortunately still very relevant. I think this is something to be raised separately, maybe with the community team, to see if it's possible to extract this content. This would be a core team decision to make. It makes sense to me that you'd want to maintain it separately (but use dependencies to require both are installed... Not strictly version locked, though). If you also want to stop maintaining those plugins, you'd probably want to talk to the content team about them taking over",2021-01-05T15:39:15Z,neutral
754734652,just pointing it out as it should not be a default setting for ansibletest as many community collections will fail it,2021-01-05T16:12:09Z,anger
754735588,same code migrated into it's own repo/utility to build html docsite,2021-01-05T16:13:36Z,anger
754740713," this is a good candidate for backporting, if you are interested ",2021-01-05T16:21:39Z,joy
754751489,"Files identified in the description: lib/ansible/modules/windows/win_shell.ps1 If these files are incorrect, please update the component name section of the description or use the !component bot command. [click here for bot help]( <! boilerplate: components_banner ",2021-01-05T16:39:23Z,anger
754751533,"Thank you very much for your interest in Ansible. Ansible has migrated much of the content into separate repositories to allow for more rapid, independent development. We are closing this issue/PR because this content has been moved to one or more collection repositories. lib/ansible/modules/windows/win_shell.ps1 For further information, please see: <! boilerplate: collection_migration ",2021-01-05T16:39:27Z,neutral
754752195,"ack, there is no requirement to run sanity testing before you upload to galaxy and the galaxy importer doesn't mandates that too. Sure the community collections would fail, but this should be surfaced to maintainers as this can be a problem users may have with your collection ",2021-01-05T16:40:57Z,fear
754783229,this looks like a sane change to me :+1:,2021-01-05T17:32:52Z,joy
754825433,"you still need a changelog, tests and to pass existing CI",2021-01-05T18:44:22Z,neutral
754849463,this PR contains the following merge commits: Please [rebase your branch]( to remove these commits. [click here for bot help]( <! boilerplate: merge_commit_notify,2021-01-05T19:29:30Z,neutral
754853123,"Files identified in the description: None If these files are incorrect, please update the component name section of the description or use the !component bot command. [click here for bot help]( <! boilerplate: components_banner ",2021-01-05T19:36:27Z,anger
754853128,": Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. Here are the items we could not find in your description: issue type component name ansible version Please set the description of this issue with an appropriate template from: [click here for bot help]( <! boilerplate: issue_missing_data ",2021-01-05T19:36:28Z,joy
754855221,"Hi Bcoca, This seems to me really contra productive to reply on a thread after almost three weeks with the answer that makes no sense! If you read carefully the information I have initially posted, you’ll notice that I wrote: “ALL HOSTS ARE NORMALLY REACHABLE, SSH KEYS HENCE PASSWORDLESS CONNECTION ARE WORKING WELL!” but the directly close the issue, seems to me a bit too quick, don’t you think? anyway, thanks for nothing,",2021-01-05T19:40:28Z,anger
754874716,We discussed this topic a bit on today's public project meeting (logs: Unfortunately nobody was around who actually uses that feature.,2021-01-05T20:17:25Z,sadness
754881609,"Since the name ansible.builtin is treated specially, it would probably make sense to use a new name, like ansible.core or ansible.base or ansible.basic, and use Ansible's to redirect all ansible.builtin.<oldnames to the new collection. If this is an option at all.",2021-01-05T20:31:21Z,neutral
754885850," Thanks! Sorry for not being there, I really thought it was going to be tomorrow... :\ I will do my best to make it to the next one. ",2021-01-05T20:39:56Z,neutral
754886143,Moved to (cleanup).,2021-01-05T20:40:34Z,neutral
754902037," Testing on the test Ansible Tower with the follwing patch leads to strange behaviour: Hmmm. I thought I added a test case for this. I see why that's happening, though. I'll keep working on it. do you have a PR for python3 module ? is the PR with changes to the module. There is no ""Python 3"" module. It is written to work with Python 2.6, 2.7, and =3.5.",2021-01-05T21:12:14Z,neutral
754903887,Please create a new PR using a branch in your fork. <! boilerplate: fork,2021-01-05T21:15:57Z,neutral
754907866,"titan, Ansible does not do host resolution in this case, it just passes the info to the ssh command, which is issuing the error you see. ",2021-01-05T21:24:13Z,fear
754935527," I believe I have fixed the behavior you were seeing. Can you test with the latest commit in ? I am still working to fix this for BSD, but it should be fixed for Linux.",2021-01-05T22:16:06Z,neutral
755048775,"Files identified in the description: [lib/ansible/plugins/connection/winrm.py]( If these files are incorrect, please update the component name section of the description or use the !component bot command. [click here for bot help]( <! boilerplate: components_banner ",2021-01-06T03:13:42Z,anger
755048777,": Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. Here are the items we could not find in your description: ansible version Please set the description of this issue with an appropriate template from: [click here for bot help]( <! boilerplate: issue_missing_data ",2021-01-06T03:13:43Z,anger
755122799,I've manually edited the module on another test system and based on my test the last commit in seems good: First pass: PLAY RECAP localhost : ok=2 changed=1 unreachable=0 failed=0 skipped=0 rescued=0 ignored=0 [root ] grep test /etc/shadow testuser1:!$6$OdJHswQFZxPKZj8K$<redacted07::: Second pass: PLAY RECAP localhost : ok=2 changed=0 unreachable=0 failed=0 skipped=0 rescued=0 ignored=0 [root ] grep test /etc/shadow testuser1:!$6$OdJHswQFZxPKZj8K$<redacted07:::,2021-01-06T06:58:21Z,fear
755128114,"Files identified in the description: lib/ansible/galaxy If these files are incorrect, please update the component name section of the description or use the !component bot command. [click here for bot help]( <! boilerplate: components_banner ",2021-01-06T07:10:32Z,anger
755131357,"Restarting tests, since now they should pass.",2021-01-06T07:18:31Z,neutral
755140157,CI is passing now (since 2.10.5 has been released and the docsite built).,2021-01-06T07:42:40Z,joy
755143948,No need to open issue for existing pull request. Closing in favor of,2021-01-06T07:51:48Z,anger
755208460,this PR contains the following merge commits: Please [rebase your branch]( to remove these commits. [click here for bot help]( <! boilerplate: merge_commit_notify,2021-01-06T10:07:53Z,neutral
755370669,Thanks for confirming. I added a test case for this scenario as well. I just need to get it fixed up for BSD now.,2021-01-06T15:35:16Z,joy
755387597,Oops! Fixed.,2021-01-06T16:01:37Z,neutral
755421849," Yes, this will be in the next set of ansiblebase releases.",2021-01-06T16:50:53Z,joy
755429189,"Oops, this problem exists in devel too, it just isn't triggered in devel. Closing in favor of doing this the right way.",2021-01-06T17:02:31Z,neutral
755461491,You should also add: HTTP_PROXY: '' HTTPS_PROXY: '' NO_PROXY: '',2021-01-06T18:01:01Z,neutral
755461876,"Files identified in the description: [lib/ansible/modules/setup.py]( If these files are incorrect, please update the component name section of the description or use the !component bot command. [click here for bot help]( <! boilerplate: components_banner ",2021-01-06T18:01:41Z,anger
755463691,This PR was evaluated as a potentially problematic PR for the following reasons: More than 50 commits. Such PR can only be merged by human. Contact a Core team member to review this PR on IRC: devel on irc.freenode.net [click here for bot help]( <! boilerplate: bad_pr,2021-01-06T18:05:02Z,fear
755521784,thanks a lot for reviewing this!!!,2021-01-06T18:59:47Z,joy
755570024,"The test ansibletest sanity test docsbuild [[explain]( failed with 1 error: docs/docsite/rst/reference_appendices/config.rst0: warning: Duplicate ID: ""envvarANSIBLE_CONNECTION_PASSWORD_FILE"". <! job_id: 3392 <! job_id: 1478a088c05b8b41db83837e8f9740b8 <! job_id: None [click here for bot help]( <! boilerplate: shippable_test_result ",2021-01-06T19:34:50Z,fear
755709305,"note that in the past we've rejected changes that push to modules the functionality of changed_when, even if we were to revise that I would not create a specific 'changes' that only deals with files but would have to be a generic ruleset and apply a standard most modules would use.",2021-01-06T21:15:39Z,sadness
755731832,would it be possible to get this merged so can proceed?,2021-01-06T21:42:26Z,neutral
755737946," note that in the past we've rejected changes that push to modules the functionality of changed_when, even if we were to revise that I would not create a specific 'changes' that only deals with files but would have to be a generic ruleset and apply a standard most modules would use. Hi , sorry I don't catch your comment. Is there anything I need to take into account regarding current changes? Could you please refer to the code if so? Thank you! ",2021-01-06T21:57:03Z,neutral
755756759,No problem from my side. I always learn a lot from you guys. I'm with you to have a different approach like running the command and check if a file was created in a separate task in a playbook.,2021-01-06T22:30:00Z,joy
755761015,"Files identified in the description: None If these files are incorrect, please update the component name section of the description or use the !component bot command. [click here for bot help]( <! boilerplate: components_banner ",2021-01-06T22:40:33Z,neutral
755761019,": Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. Here are the items we could not find in your description: component name Please set the description of this issue with an appropriate template from: [click here for bot help]( <! boilerplate: issue_missing_data ",2021-01-06T22:40:34Z,joy
755955980," Any thoughts about this PR? The only missing part is to decide if we change the literal by literal_search I vote for literal as we have also regex and not regex_search. Once decided, I think the solution is implemented and the PR ready. Thank you!",2021-01-07T08:07:01Z,fear
755956260,Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to Please resubmit this issue in the above repository. If you have further questions please stop by IRC or the mailing list: IRC: on irc.freenode.net mailing list:,2021-01-07T08:07:32Z,neutral
756048945,"Files identified in the description: lib/ansible/galaxy If these files are incorrect, please update the component name section of the description or use the !component bot command. [click here for bot help]( <! boilerplate: components_banner ",2021-01-07T11:06:19Z,anger
756083768,"destination_port is of type string, see The documentation states that explicitly and the description gives several reasons why that is needed: you can specify service names or provide port ranges. This obviously doesn't work with pure integers :)",2021-01-07T12:20:50Z,neutral
756146680,"Files identified in the description: [lib/ansible/modules/file.py]( If these files are incorrect, please update the component name section of the description or use the !component bot command. [click here for bot help]( <! boilerplate: components_banner ",2021-01-07T14:22:45Z,anger
756150944,"You are right , my bad.",2021-01-07T14:30:09Z,sadness
756159494,Would it be possible to merge this PR? Otherwise I've to cope with the stale_ci label every other week or so ;) Let me know if there are any other things I should do ...,2021-01-07T14:45:00Z,neutral
756178533,"Files identified in the description: None If these files are incorrect, please update the component name section of the description or use the !component bot command. [click here for bot help]( <! boilerplate: components_banner ",2021-01-07T15:16:13Z,anger
756181337,Sorry about the noise. I was worried that consolidating that logic would result in some new warnings that were not there before. I'll work on a solution.,2021-01-07T15:20:54Z,fear
756188310,Probably is good closing too?,2021-01-07T15:31:45Z,neutral
756190898," You don't have to worry about stale_ci. If tests passed, we'll rerun them before merging. This PR sparked some internal discussion around the need to have a good way to allow adding support for iptables extensions in a way that would fail nicely if the extension was not installed. I [opened a feature request]( for that. I was trying to determine if the set extension is in the default extensions provided by iptables. It seems like it is, but I wasn't able to 100% verify that. Do you know if this is in the default set of extensions?",2021-01-07T15:35:53Z,fear
756201214,"Files identified in the description: None If these files are incorrect, please update the component name section of the description or use the !component bot command. [click here for bot help]( <! boilerplate: components_banner ",2021-01-07T15:52:01Z,anger
756201224,": Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. Here are the items we could not find in your description: component name Please set the description of this issue with an appropriate template from: [click here for bot help]( <! boilerplate: issue_missing_data ",2021-01-07T15:52:02Z,joy
756201895,"After reviewing the feature a bit more, we have decided we do not include this feature. See for details.",2021-01-07T15:52:53Z,sadness
756202901,I'm planning to get rid of this noisy warning in 2.11.,2021-01-07T15:54:21Z,fear
756223092,"This may not be easy to fix. The problem is that AnsibleVaultEncryptedUnicode does not inherit from a string type, but implements the methods to function as a string. In both our urlencode filter (used with jinja2<2.7) and in upstream jinja2, there are isinstance checks which prevents it from being treated as a string. More work would need to be done to test this, but on the surface, this change to AnsibleVaultEncryptedUnicode allows for it to work: python def __class__(self): return text_type def __copy__(self): return self def __deepcopy__(self, args, kwargs): return self (The above breaks a lot of stuff)",2021-01-07T16:26:51Z,fear
756223762,Do you know if this is in the default set of extensions? Yes it is. Since 1.2.10 ( which was released back in 2004.,2021-01-07T16:27:59Z,neutral
756226947," I hope there's a chance of backporting str_strict to 2.9, because otherwise it will take many, many years until it can be used (until 2.9 is dead)...",2021-01-07T16:33:26Z,neutral
756231166,ansible_failed_task and ansible_failed_result are available in rescue for precisely this use case. See,2021-01-07T16:40:42Z,sadness
756232728,Duplicate of,2021-01-07T16:43:12Z,neutral
756239258,"The issue here seems to be that you are using python2 on the target host, and not python3. You can see this here: TASK [Install python3apt] [WARNING]: Updating cache and autoinstalling missing dependency: pythonapt ok: [instance] That would WARNING would have indicated python3apt if you were executing python3. As such, when you run the pip module, it also expects that pip be installed for the python2 interpreter being used. Otherwise, you can set executable: pip3 in your task.",2021-01-07T16:54:03Z,anger
756240823,"If you check above, the first run installs python3apt correctly ( On the second run, it installs pythonapt v2. Why would that be done?",2021-01-07T16:56:32Z,neutral
756241540,Or should this be set for Ubuntu specifically?,2021-01-07T16:57:46Z,neutral
756242713,Your /usr/local/bin/python2 is missing the Python stdlib ast module: This indicates that your python install does not contain all necessary features. You will need to investigate how to install this module on your platform or rebuild python so that it is included. If you have further questions please stop by IRC or the mailing list: IRC: on irc.freenode.net mailing list:,2021-01-07T16:59:46Z,fear
756244926," On the second run, it installs pythonapt v2. Why would that be done? That indicates that python2 wasn't available when the first playbook execution happened, and it was installed during that first execution. Then the 2nd execution discovered that py2 was available and used it. Our python auto discovery still prefers /usr/bin/python if found. See for how to change that behavior.",2021-01-07T17:03:17Z,fear
756246832,"Its quite beyond me how a task that installs the ""python3apt"" package installs the python2 vesion of that package without warning about this right away or failing",2021-01-07T17:06:04Z,anger
756250661,"Our modules are written in python, and they often uses the Python APIs for interacting with things like apt. Since you are executing /usr/bin/python (python2) on the target, it requires those python API bindings, and thus auto installs pythonapt for you so that it can perform it's job. Effectively you are telling python2, to install python3apt, but to do so, python2 needs pythonapt to achieve that result.",2021-01-07T17:09:37Z,anger
756254066,Rebased after has been merged. ready_for_review,2021-01-07T17:15:34Z,joy
756256618,The topic was again skipped today. The next meeting is next Tuesday at 19:00 UTC.,2021-01-07T17:20:15Z,joy
756260249,Sorry about missing again. Is there anything we can talk about here that would help?,2021-01-07T17:25:54Z,sadness
756264680,"If you just want documentation, you can start by reading If you wish the decision to be reversed, you will need to attend the IRC meeting with the intention of convincing the core team to reverse the decision.",2021-01-07T17:33:25Z,joy
756267921,"I fail to see what this reddit comment is supposed to document. Is it ""why was the hash_behaviour=merge deprecated?"" or ""what are hash_behaviour=merge's alternatives?"" ?",2021-01-07T17:39:06Z,anger
756276051,"Thanks for pointing me out the solution , sorry for inconvenience! ",2021-01-07T17:53:16Z,anger
756306478,it looks like the string.replace() changes got lost in your rebase? Not seeing them in the current diff.,2021-01-07T18:45:57Z,sadness
756323846,"The python3apt library is only available to the system Python and not available in virtual environments. When you are using the [implicit localhost]( it is necessary to specify the system Python interpreter. On a task, you would have to define ansible_python_interpreter. To discuss this further, please reach out on IRC or the mailing list:    IRC: devel on irc.freenode.net      mailing list: ",2021-01-07T19:17:40Z,neutral
756326182,"Ansible 2.8 is near end of life and is currently only receives security fixes. This works in Ansible = 2.9. Please upgrade to a newer Ansible version. To discuss this further, please reach out on IRC or the mailing list:    IRC: on irc.freenode.net      mailing list: ",2021-01-07T19:22:24Z,fear
756328060,Closing as a duplicate of We are discussing other collection level directories that would be helpful to have.,2021-01-07T19:25:55Z,joy
756329495,"When this feature is implemented, the documentation change in needs to be removed.",2021-01-07T19:28:40Z,neutral
756333897,This change looks accurate can you please [rebase your branch]( so we can merge this? Thanks!,2021-01-07T19:33:17Z,joy
756334600,"Looks good, thanks . I'll kick off a fresh CI run and merge this once it passes.",2021-01-07T19:34:32Z,joy
756335575,"You will need to add those ciphers to your ssh_config in order to connect to the device. Newer versions of openssh disable older ciphers by default. To discuss this further, please reach out on IRC or the mailing list:    IRC: on irc.freenode.net      mailing list: ",2021-01-07T19:36:22Z,neutral
756339656,This seems like a misunderstanding when or how to use become on a task. This is best solved by discussing on IRC or the mailing list:    IRC: on irc.freenode.net      mailing list:,2021-01-07T19:43:40Z,anger
756342474,"We have been looking at and experimenting with different process models in Ansible ( I'm going to close this since we don't have plans to work on it currently and don't like to keep feature requests open indefinitely. But we are aware of this and plan to make changes in the future. To discuss this further, please reach out on IRC or the mailing list:    IRC: devel on irc.freenode.net      mailing list: ",2021-01-07T19:47:48Z,anger
756344290,"Could you provide more output from the task with vvvvvv? Also, IRC may be a good place to ask for help if this a connection issue and not a bug.    IRC: windows or on irc.freenode.net   needs_info",2021-01-07T19:50:50Z,neutral
756346576,Thanks and .,2021-01-07T19:55:09Z,neutral
756351138,"According to your task output, you are not targeting 127.0.0.1 as defined in inventory, but targeting instance which is created for you by molecule as a docker container.",2021-01-07T20:03:33Z,joy
756353093,"Files identified in the description: [lib/ansible/modules/lineinfile.py]( If these files are incorrect, please update the component name section of the description or use the !component bot command. [click here for bot help]( <! boilerplate: components_banner ",2021-01-07T20:07:04Z,anger
756362587,I believe this is a duplicate of the already resolved,2021-01-07T20:24:35Z,neutral
756363107,"I believe the problem is that you did not supply follow: false, and the permissions were set on the target, and not the symlink itself.",2021-01-07T20:25:33Z,anger
756363203,thanks for reviewing and merging!,2021-01-07T20:25:47Z,joy
756379586,"Hm.. that's true, didnt realize that molecule actually isn't using the inventory file. I will close this, thank you for the help",2021-01-07T20:57:03Z,joy
756387043,Wiill try that tomorrow. I am currently testing a migration from Ansible 2.8 to Ansible 2.10 and that would be an unexpected behavior change of the module. Will crawl through the changelog again...,2021-01-07T21:11:53Z,fear
756389831,The test ansibletest sanity test yamllint [[explain]( failed with 2 errors: lib/ansible/plugins/lookup/sequence.py1: error: EXAMPLES: syntax error: could not find expected ':' (syntax) lib/ansible/plugins/lookup/sequence.py1: unparsablewithlibyaml: while scanning a simple key could not find expected ':' <! job_id: 3583 <! job_id: a29d3a57f51ba8398f8a6cfcc15c3ee4 <! job_id: None The test ansibletest sanity test pep8 [[explain]( failed with 1 error: lib/ansible/plugins/lookup/sequence.py44: W291: trailing whitespace <! job_id: 3583 <! job_id: e28caff85f6daf4f21fbcac28d8e8e7c <! job_id: None [click here for bot help]( <! boilerplate: shippable_test_result,2021-01-07T21:17:32Z,fear
756392391,This fix appears to have been done for the 2.9 release and would seem related: It fixed a bug where the creation of a link (attributes applied to the link) differed from ensuring the link (attributes applied to the target) on subsequent runs. That change ensured that with follow: yes (which is the default) that it always applied to the target and not the link.,2021-01-07T21:21:13Z,fear
756397440,rebuild_merge,2021-01-07T21:30:27Z,neutral
756397940,"Thanks. Tested this for the issue I was currently seeing while porting from 2.9.10 to 2.10.4. Works well enough to let me know what was deprecated... [DEPRECATION WARNING]: community.general.actionable has been deprecated. see plugin documentation for details. This feature will be removed from community.general in version 2.0.0. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg. I actually want to add that about 10 minutes later I was able to figure out what we were calling that was making this error be deprecation warning be displayed. So, thank you and I hope this patch makes it in!",2021-01-07T21:31:26Z,fear
756402501,"There may still be bugs related to this on DragonFlyBSD, OpenBSD, and NetBSD. Since I don't have an easy way to test on those OSs, I'm not going to change the code for fear of breaking existing functionality. It was nontrivial to get this fixed correctly for FreeBSD.",2021-01-07T21:41:09Z,fear
756428390,"Looks good, thanks ! ",2021-01-07T22:32:48Z,joy
756429598,"This change will appear in the devel documentation within 24 hours. If you'd like to see it appear in the latest documentation also, feel free to open a [backport PR]( ",2021-01-07T22:35:54Z,joy
756435146," Yes, it seems string.replace() issue was resolved in this commit: My pull request is duplicate to the commit. So I'd close the request.",2021-01-07T22:51:38Z,anger
756456450,This PR contains @ mentions in at least one commit message. Those mentions can cause cascading notifications through GitHub and need to be removed. Please squash or amend your commits to remove the mentions. [click here for bot help]( <! boilerplate: commit_msg_mentions,2021-01-07T23:50:40Z,fear
756458861,"Files identified in the description: lib/ansible/modules/net_tools/dnsimple.py If these files are incorrect, please update the component name section of the description or use the !component bot command. [click here for bot help]( <! boilerplate: components_banner ",2021-01-07T23:57:39Z,anger
756458865,"Thank you very much for your interest in Ansible. Ansible has migrated much of the content into separate repositories to allow for more rapid, independent development. We are closing this issue/PR because this content has been moved to one or more collection repositories. lib/ansible/modules/net_tools/dnsimple.py For further information, please see: <! boilerplate: collection_migration ",2021-01-07T23:57:39Z,neutral
756476909," Perhaps we could do one of the following to improve the transition while maintaining backwards compatibility? 1. Require setting an environment variable to optin to the new behavior. This would only be needed for the backports. 2. Provide another version of the scripts (such as a _v2 suffixed) that would provide the new behavior. This would be needed in all supported branches. I think the first option is the most appealing, since it wouldn't require a separate script and the additional logic would only be needed for the backports.",2021-01-08T00:51:13Z,anger
756556328,"The more I think about this, the more I'm wondering if there really is much of a backwards compatibility concern here. Yes, we're using a different tool to create the virtual environment, but it should provide the same behavior in the end. If a virtual environment was created before, it should still be. If it was failing to create a virtual environment before, then the test would already be failing making it pass shouldn't be a problem.",2021-01-08T05:31:12Z,fear
756572095,"As long as it suffices to set the env variable in the test scripts (and not when calling ansibletest), that's fine for me. But your new argument sounds reasonable to me as well.",2021-01-08T06:17:27Z,anger
756572668," thanks, your rewording sounds good! :)",2021-01-08T06:19:08Z,joy
756572831,thanks for reviewing and merging!,2021-01-08T06:19:41Z,joy
756574225,Thank you . This does indeed work. Seems like i was not that concentrated enough yesterday. Sorry for this issue.,2021-01-08T06:23:42Z,sadness
756646558," Still need to decide about 'RHEV' RHEV has been renamed to RHV in RHV 4.0, which was released in August 2016, so the last version with RHEV name 3.6, which is completely unsupported from September 2018. So from my point of view we don't need to worry about change from RHEV to RHV anymore",2021-01-08T09:21:37Z,fear
756650499,I have added a new commit that could support both rhv and rhev for backward compatibility in the worst case I can reset the commit.,2021-01-08T09:29:18Z,sadness
756691673,"Files identified in the description: lib/ansible/modules/cloud/amazon/ec2_instance.py If these files are incorrect, please update the component name section of the description or use the !component bot command. [click here for bot help]( <! boilerplate: components_banner ",2021-01-08T10:55:03Z,anger
756691683,", just so you are aware we have a dedicated Working Group for aws. You can find other people interested in this in aws on Freenode IRC For more information about communities, meetings and agendas see [click here for bot help]( <! boilerplate: community_workgroups ",2021-01-08T10:55:04Z,joy
756691688,"Thank you very much for your interest in Ansible. Ansible has migrated much of the content into separate repositories to allow for more rapid, independent development. We are closing this issue/PR because this content has been moved to one or more collection repositories. lib/ansible/modules/cloud/amazon/ec2_instance.py For further information, please see: <! boilerplate: collection_migration ",2021-01-08T10:55:05Z,fear
756735147,!needs_collection_redirect,2021-01-08T12:39:24Z,neutral
756735483,"Files identified in the description: None If these files are incorrect, please update the component name section of the description or use the !component bot command. [click here for bot help]( <! boilerplate: components_banner ",2021-01-08T12:40:21Z,anger
756735487,": Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. Here are the items we could not find in your description: component name Please set the description of this issue with an appropriate template from: [click here for bot help]( <! boilerplate: issue_missing_data ",2021-01-08T12:40:21Z,joy
756746153,I can't see how the solution you mention could help on this one.. can you please explain?,2021-01-08T13:06:21Z,joy
756801549,"Files identified in the description: lib/ansible/playbook If these files are incorrect, please update the component name section of the description or use the !component bot command. [click here for bot help]( <! boilerplate: components_banner ",2021-01-08T15:03:18Z,anger
756804489,closing as per above.,2021-01-08T15:08:26Z,neutral
756806449,"Files identified in the description: [lib/ansible/modules/copy.py]( If these files are incorrect, please update the component name section of the description or use the !component bot command. [click here for bot help]( <! boilerplate: components_banner ",2021-01-08T15:11:39Z,anger
756807324,also need 'global' fix for dwim by passing in error/warning required by caller from the global errors that lookups now have.,2021-01-08T15:13:08Z,fear
756809235,proxy suport was added to the internal fetch_file function that apt_key uses so this is fixed in newer versions.,2021-01-08T15:16:14Z,fear
756809884,closing as per,2021-01-08T15:17:10Z,neutral
756812883,reclassified as this is still correct for ansibletest's main usage but we can add a feature to disable this check for those using it outside the ansible repo.,2021-01-08T15:22:24Z,neutral
756814037,closing as subset,2021-01-08T15:24:27Z,neutral
756814698,Dupe of,2021-01-08T15:25:43Z,neutral
756816066,we still have no reproducer of this nor any other reports of this issue happening with other editors. is this still and issue? have you been able to reproduce in any other way? needs_info,2021-01-08T15:28:12Z,anger
756816646,anything still missing on this? needs_info,2021-01-08T15:29:13Z,sadness
756817459,"it is already mentioned in third party utilities, we believe this is sufficient for now.",2021-01-08T15:30:32Z,neutral
756820486,closing as per above,2021-01-08T15:35:52Z,neutral
756820883,"Files identified in the description: None If these files are incorrect, please update the component name section of the description or use the !component bot command. [click here for bot help]( <! boilerplate: components_banner ",2021-01-08T15:36:29Z,anger
756821162,mostly implemented in,2021-01-08T15:37:04Z,neutral
756823747,closing as per above,2021-01-08T15:41:41Z,neutral
756824947,"Thanks . I'll merge now, and the new example will appear in the devel docs within 24 hours. If you'd also like to see it in the latest docs, feel free to open a [backport PR]( ",2021-01-08T15:43:48Z,joy
756825905,"Files identified in the description: [lib/ansible/modules/package.py]( [lib/ansible/modules/yum.py]( If these files are incorrect, please update the component name section of the description or use the !component bot command. [click here for bot help]( <! boilerplate: components_banner ",2021-01-08T15:45:38Z,anger
756825971,closing as per above,2021-01-08T15:45:45Z,neutral
756826984,closing as the original issue is mostly a misunderstanding and now the issue is trending into different discussions more appropriate for core IRC meetings.,2021-01-08T15:47:37Z,anger
756827987,"Thanks for noticing and fixing that, . I have no idea why the CI suite is failing, but it is not related to this change. I will investigate.",2021-01-08T15:49:09Z,sadness
756831323,Closing since we cannot reproduce and also do not believe this is an issue as we do handle templating post queue.,2021-01-08T15:54:32Z,fear
756833698,waiting_on_contributor,2021-01-08T15:58:34Z,neutral
756836080," Thanks for keeping tabs on these older issues! I just tested it and also cannot reproduce this anymore. So, this has been fixed somewhere in the last 2 years.",2021-01-08T16:02:30Z,neutral
756841513,"note: we can add a 'vault file extension' config (default to .vault) but would 'multiply it' with existing yaml/vars file extensions to avoid collisions with other vaulted content. i.e ( .json.vault, .yaml.vault, etc)",2021-01-08T16:09:15Z,neutral
756864080,"When using python2 did you have libselinuxpython installed? If you didn't then ansible would not have set selinux context on the files. Curious if this is something different between py2 vs py3, or whether you've introduced selinux python APIs into the equation when they weren't with py2.",2021-01-08T16:46:46Z,fear
756897819,"I updated the macOS 11 image to 11.1 and Python 3.9.1 as well as removed virutalenv. I think that should resolve the last test issue. As a bonus, the 11.1 image is 2GB smaller than the 11.0 image.",2021-01-08T17:34:55Z,fear
756904404,The test ansibletest sanity test docsbuild [[explain]( failed with 1 error: docs/docsite/rst/reference_appendices/config.rst0: warning: malformed hyperlink target. <! job_id: 3635 <! job_id: 3f0a6b591293b8ffcf02ea5c54c30cf8 <! job_id: None [click here for bot help]( <! boilerplate: shippable_test_result,2021-01-08T17:49:03Z,fear
756938401,Yes we had libselinuxpython installed. We've had selinux enabled when running with py2 and py3. But it seemed like when running Ansible with py3 that the selinux permissions were not correct.,2021-01-08T19:00:24Z,joy
756942503,/azp run,2021-01-08T19:09:08Z,neutral
756946179,"Thank you for your interest in the Ansible documentation. Unfortunately, these changes do not match the overall Ansible [documentation style]( If you have questions about the documentation, or about using Ansible, you can [contact the Ansible community]( for answers.",2021-01-08T19:16:14Z,neutral
756949295,apologies for leaving open its all clear,2021-01-08T19:23:46Z,sadness
756959932,thanks for reviewing and merging!,2021-01-08T19:48:43Z,joy
756962855,"This is an improvement, thanks and . I've committed the last whitespace correction and will merge as soon as the latest commit passes our CI suite.",2021-01-08T19:55:36Z,fear
756966152," I like duplicated, which is clearly an adjective; duplicate is less clear because it can be an adjective or a verb.",2021-01-08T20:02:56Z,neutral
756968984,Thanks and sorry I dropped the ball on this over the holidays. I'll try to get it merged now.,2021-01-08T20:08:58Z,sadness
756969466,<samp Azure Pipelines successfully started running 1 pipeline(s).<br </samp,2021-01-08T20:09:58Z,joy
756969536,/azp run,2021-01-08T20:10:10Z,neutral
756980392,Closing per discussion in,2021-01-08T20:21:57Z,neutral
756990344,thanks!,2021-01-08T20:46:10Z,joy
757000476," thanks, that would be awesome :D",2021-01-08T21:12:49Z,joy
757012395," I've opened backports for stable2.10 and stable2.9: After discussing with we decided to go with optin behavior, just to be safe. To optin to the new behavior in those branches, tests will need to set the ANSIBLE_TEST_PREFER_VENV environment variable. So something like this would work: bash export ANSIBLE_TEST_PREFER_VENV=1 source virtualenv.sh Whereas before the tests simply used: bash source virtualenv.sh This should allow a single test configuration to work across 2.9, 2.10 and devel once the backports are merged.",2021-01-08T21:44:40Z,fear
757021171,Thanks . Backport PR raised,2021-01-08T22:02:31Z,joy
757044418,This pullrequest is waiting for your response. Please respond or the pullrequest will be closed. [click here for bot help]( <! boilerplate: needs_info_base,2021-01-08T23:18:59Z,anger
757119806,"Files identified in the description: None If these files are incorrect, please update the component name section of the description or use the !component bot command. [click here for bot help]( <! boilerplate: components_banner ",2021-01-09T09:04:00Z,anger
757119809,": Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. Here are the items we could not find in your description: component name Please set the description of this issue with an appropriate template from: [click here for bot help]( <! boilerplate: issue_missing_data ",2021-01-09T09:04:00Z,joy
757371089," great, thanks! I've tried it out in ansiblecollections/community.hashi_vault, works perfectly!",2021-01-09T21:39:26Z,joy
757441434,"This is strange. Sphinx 2.1.2 ( already has add_css_file ( Maybe an even older version of Sphinx is used here? It must have been before version 1.8.0, since add_css_file was added then ( This should get fixed by ansiblecommunity/antsibull, but maybe the very old Sphinx version used for docsite testing also needs to be updated :)",2021-01-10T08:58:32Z,fear
757457344,Can confirm the same issue in ansible 2.10.4,2021-01-10T11:08:04Z,sadness
757463384,"By default, Ansible [replaces the hash in the variables]( In your case, the value of nginx is replaced by the one configured in nx2.yml, which is {'servername5': 'nx.server5.com', 'servername6': 'nx.server6.com'}, so nginx.servername1 is not actually available in the end. If you want Ansible to merge(update) your hash instead of replace it, you need to configure it specifically. Via environment variables bash ANSIBLE_HASH_BEHAVIOUR=merge ansibleplaybook roles/test/tasks/main1.yml Or via ansible.cfg ini [defaults] hash_behaviour = merge Cheers!",2021-01-10T11:51:37Z,anger
757478921," Enabling passwordless sudo for rsync seems to do the trick for me: yaml lineinfile: path: /etc/sudoers state: present insertafter: EOF line: '{{ ansible_user }} ALL=NOPASSWD:/usr/bin/rsync' Attention, that gives the connecting user root access to the entire system. you shouldn't trade security for convenience, IMHO.",2021-01-10T13:46:09Z,anger
757512056," You have not responded to information requests in this issue so we will assume it no longer affects you. If you are still interested in this, please create a new issue with the requested information. [click here for bot help]( <! boilerplate: needs_info_base ",2021-01-10T17:24:38Z,anger
757636931,"Hi, any updates on this?",2021-01-11T05:46:11Z,neutral
757649336,and thanks for this one as well :),2021-01-11T06:22:26Z,joy
757659181,i resolved the conflict ready_for_review,2021-01-11T06:49:16Z,joy
757662420,This probably merits a retroactive changelog entry.,2021-01-11T06:57:31Z,neutral
757853479,I just need to add: follow: no,2021-01-11T10:17:01Z,sadness
757934294,"I do not have the time this week to test this, but this will probably solve the issue. I had forgotten that I had to revert to the default ansible of ubuntu since the upgrade to 20.04 and was no longer up to date, I apologise for the trouble. Thanks for the reply.",2021-01-11T12:55:51Z,sadness
757984294,Thanks !,2021-01-11T14:25:15Z,neutral
757993327,"What if the ansible.builtin.command, ansible.builtin.script or ansible.builtin.shell plugins are used? None of those provide a parameter to create worldwriteable files. I know for a fact we need this to work to make sure the task does not fail.",2021-01-11T14:39:44Z,fear
758013246," the shell plugin is used to execute the commands around modules (make temp, copy files, cleanup) and the modules themselves (except script/raw) so it doesn't matter the action used.",2021-01-11T15:12:01Z,fear
758056085," this is fixed in newer versions. Which is ""newer""? Newer than 2.7?",2021-01-11T16:09:54Z,fear
758084409,"I've changed the IP addresses, names, and playbook name in the ansibleplaybook run to obscure sensitive data.",2021-01-11T16:55:27Z,neutral
758088985," Looks good. I recommend including a comment when setting the env var that it is only needed while supporting 2.9 and 2.10, so that it will be more obvious in the future when it can be removed.",2021-01-11T17:02:51Z,joy
758093484,"I'll salvage the tests, but the rest of this will be implemented pretty differently closing this to start from scratch.",2021-01-11T17:10:30Z,neutral
758130980,CC about the older Sphinx requirement,2021-01-11T18:15:08Z,neutral
758149074," that still does not tell me where to put the replacement for this: ini [defaults] allow_world_readable_tmpfiles=true The deprecation warning says support for this will go away, and I noticed that having this here without deprecation_warnings=false even reports the job as failed.",2021-01-11T18:48:17Z,fear
758152525,FYI there's a PR allowing better sphinx:,2021-01-11T18:54:09Z,neutral
758153152," This particular table row is baffling: Is there a world_readable_temp option in the plugin section, or is that a truncated reference to the global setting? This would be a great place to be explicit about how to utilize it correctly. That is the internal parameter name, and is generally of no concern for users. What you are interested in, is the information in the Configuration column. The parameter name, and the configuration names are not always the same.",2021-01-11T18:55:15Z,fear
758157900," it looks like both the and specify allow_world_readable_tmpfiles as the INI key under defaults. If we intended on not renaming allow_world_readable_tmpfiles to shell_allow_world_readable_tmpfiles, then we probably need to remove the deprecation in base.yml or remove the entry entirely.",2021-01-11T19:03:31Z,neutral
758177038,"In any case, whatever comes first ( merged or new antsibull release), this issue should be fixed soon :)",2021-01-11T19:38:18Z,joy
758218704,hertel Can we get a test for this (and probably retroactively in devel) before we pull it into the stable branches?,2021-01-11T20:57:43Z,neutral
758298435,", just so you are aware we have a dedicated Working Group for network. You can find other people interested in this in network on Freenode IRC For more information about communities, meetings and agendas see [click here for bot help]( <! boilerplate: community_workgroups ",2021-01-11T23:53:57Z,joy
758298437,"Thank you very much for your interest in Ansible. Ansible has migrated much of the content into separate repositories to allow for more rapid, independent development. We are closing this issue/PR because this content has been moved to one or more collection repositories. lib/ansible/modules/network/aireos/aireos_command.py For further information, please see: <! boilerplate: collection_migration ",2021-01-11T23:53:58Z,neutral
758298599,"for what it's worth, I ""resolved"" this issue by installing python3 and set ansible to find the binary",2021-01-11T23:54:26Z,neutral
758305732,"Thanks, I think I am already using python3.9 ansible version | grep ""python version"" python version = 3.9.1 (default, Jan 8 2021, 1743) [Clang 12.0.0 (clang1200.0.32.28)]",2021-01-12T00:15:38Z,joy
758517861,what‘s mean it？ I just add the group，then how to ask question? ![image]( ’,2021-01-12T09:14:04Z,neutral
758667159,"shekhar: Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. Here are the items we could not find in your description: component name Please set the description of this issue with an appropriate template from: [click here for bot help]( <! boilerplate: issue_missing_data ",2021-01-12T13:50:30Z,joy
758679822," The variable ansible_play_hosts actually does not includes failed or unreachable hosts Ah, sorry, my statement above was partially wrong. After doing some additional experiments, we found ansible_play_hosts may include unreachable hosts in some cases. Especially, failed host foo2 is _excluded_ from ansible_play_hosts in the first play (foo1 and foo2): failed host foo2 is _excluded_ from ansible_play_hosts in the second play (foo3): unreachable host foo2 is _excluded_ from ansible_play_hosts in the first play (foo1 and foo2): unreachable host foo2 is _included_ in ansible_play_hosts in the second play (foo3): Do you have any suggestions to fix?",2021-01-12T14:11:45Z,sadness
758729726,"note: we have duplicate options for collection paths, with different spellings.",2021-01-12T15:24:40Z,neutral
758730926,"I think we would need to verify whether this is handled on nix via SSH as well. If it doesn't, we probably shouldn't do this for Windows.",2021-01-12T15:26:29Z,fear
758731249,There are several things going on here: 1. We have incorrect/inconsistent options that need to be corrected: collectionspath vs collectionpath 2. was just merged yesterday and will be in the next release. 3. What is the value of . in your command line? The value of collectionspath replaces the list of default paths.,2021-01-12T15:26:57Z,anger
758731998,the intention of . was to give it a path so it stops complaining that none of the provided paths are usable.,2021-01-12T15:28:07Z,fear
758733103,"This is very possibly related to the timeout, which can be adjusted using the following configuration Can you test applying that configuration to a longer timeout, and verify whether all mount information is retrieved? needs_info",2021-01-12T15:29:06Z,neutral
758738350,"We have discussed this in our triage, and have decided not to pursue this further. Closing per above, as this is a git problem, and we don't want to add arbitrary git version inspection. If you have further questions please stop by IRC or the mailing list: IRC: on irc.freenode.net mailing list: ",2021-01-12T15:34:07Z,neutral
758740530,This issue was resolved by This will require that you upgrade to the most recent 2.9.16 and disable remote syslog logging to get around the issue. Or ensure that the NULL character is not included. by setting no_target_syslog to True in your Ansible config If you have further questions please stop by IRC or the mailing list: IRC: on irc.freenode.net mailing list:,2021-01-12T15:37:16Z,fear
758742748,"All data loaded from lookup is marked as ""unsafe"" which means we explicitly will not template it. I'd recommend using vars_files within the play from provision.yml If you have further questions please stop by IRC or the mailing list: IRC: on irc.freenode.net mailing list: ",2021-01-12T15:40:27Z,neutral
758744196,"This issue is either related to a misconfigured machine, or a problematic network connection. You may wish to add an until on the task to loop until successful install, which we have to use in CI sometimes due to network interruptions or mirrors that are misbehaving. If you have further questions please stop by IRC or the mailing list: IRC: on irc.freenode.net mailing list: ",2021-01-12T15:42:34Z,neutral
758744531,Fragment added. Done.,2021-01-12T15:43:03Z,joy
758750354,thoughts on this?,2021-01-12T15:51:45Z,sadness
758751906,This change is backwards incompatible for users relying on the fact that directory is relative to /,2021-01-12T15:53:59Z,fear
758753298,"This will need a changelog fragment, as well as integration tests.",2021-01-12T15:56:18Z,neutral
758764082,I have added a test based on the existing ones. Please let me know if you need any change/improvement in the test,2021-01-12T16:12:31Z,neutral
758767226,One other thing that was brought up: should this be a warning not an error?,2021-01-12T16:17:10Z,fear
758774005," I would expect it to be a warning. ""The list is empty"" is a valid answer, not an error.",2021-01-12T16:27:32Z,anger
758775815,"Since it is completing in far under the timeout, I'd have to guess that one of the operations may be producing an OSError. To troubleshoot, you could try testing all the code from lib/ansible/module_utils/facts/utils.py:get_mount_size You could hack that function to raise instead of pass to see if you can get more info. In short, I don't think we are going to be much help, since we cannot reproduce this. As such, debugging the cause is likely going to be your responsibility.",2021-01-12T16:30:14Z,neutral
758788517,If I modify it to print out the exception it is a permissions issue. Seems when the system is locked down you have to either run the entire playbook with become:True or rerun the gather facts with it. Makes sense now that I see it. Thanks for you help. Edited out the erroneous fact that df can still show the sizes when not root.,2021-01-12T16:49:58Z,neutral
758796546,"Well, if there are zero valid paths, then it's an error, I guess. If there are any legitimate paths, then empty list would make sense to say ""the list is empty"" w/o erroring out, I guess.",2021-01-12T16:57:57Z,anger
758798501,"If the list is supposed to be empty, why should there be legitimate paths? It should only be an error if you actually need at least one path to exist (f.ex. while installing).",2021-01-12T17:00:09Z,anger
758826880,note that we have it x2 do we really need both instances?,2021-01-12T17:45:58Z,neutral
758830071,Thank you very much,2021-01-12T17:51:24Z,joy
758867260,I think I had it as shared originally but ran into problems trying to reuse across sub commands.,2021-01-12T18:57:26Z,fear
758885350,"Keys are not templated in dictionaries, only values. You can create a template file and use the template lookup to render your data the way you want. There are several examples around for using lookup with definition. See: If you have further questions please stop by IRC or the mailing list: IRC: on irc.freenode.net mailing list: ",2021-01-12T19:31:13Z,neutral
758895680,That was my work around. Wasn't ideal but did work.,2021-01-12T19:50:40Z,joy
758916543,fwiw the Ansible maintained collections talk about versioning and deprecation and their own flare of 'maintained' collections that can last 2 years,2021-01-12T20:18:42Z,joy
758917227,"For the result of conversations about this, see ",2021-01-12T20:19:28Z,neutral
758938486,"it is still an issue, I am getting these exact errors with just around 120150 existing VMs in VMSSs in our region. Does it have a permanent fix in new Ansible versions or I should turn off batch mode? I use ansible 2.9.1 ",2021-01-12T20:34:41Z,anger
758950713,"Instead of redirects, we should put stub pages, or a special 404 to say 'hey Ansible is different from ansiblecore, go here for ansiblecore xxx files'.",2021-01-12T20:40:08Z,neutral
758958917,"Thank you very much for your interest in Ansible. Ansible has migrated much of the content into separate repositories to allow for more rapid, independent development. We are closing this issue/PR because this content has been moved to one or more collection repositories. lib/ansible/plugins/inventory/azure_rm.py For further information, please see: <! boilerplate: collection_migration ",2021-01-12T20:45:37Z,neutral
758984626,"Files identified in the description: None If these files are incorrect, please update the component name section of the description or use the !component bot command. [click here for bot help]( <! boilerplate: components_banner ",2021-01-12T21:01:21Z,anger
758984639,"shah100: Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. Here are the items we could not find in your description: component name Please set the description of this issue with an appropriate template from: [click here for bot help]( <! boilerplate: issue_missing_data ",2021-01-12T21:01:22Z,joy
759033013,"I've been going round and round trying to work out the desired behavior. I'm going to have to look again tomorrow. I want to say something like env ANSIBLE_COLLECTIONS_PATHS='' ansiblegalaxy collection list should silently list nothing, but I think that may depend on the presence of external dirs and whether or not they contain an ansible_collections subdir.",2021-01-12T21:34:23Z,fear
759063448,"Thank you very much for your interest in Ansible. Ansible has migrated much of the content into separate repositories to allow for more rapid, independent development. We are closing this issue/PR because this content has been moved to one or more collection repositories. lib/ansible/modules/network/nxos/nxos_config.py For further information, please see: <! boilerplate: collection_migration ",2021-01-12T22:00:39Z,joy
759200048," Please fill the issue template which helps us to identify the issue. Also, provide playbooks used, console log, and Ansible version? ",2021-01-13T04:38:25Z,neutral
759313465,"Thank you very much for your interest in Ansible. Ansible has migrated much of the content into separate repositories to allow for more rapid, independent development. We are closing this issue/PR because this content has been moved to one or more collection repositories. lib/ansible/modules/database/mysql/mysql_replication.py For further information, please see: <! boilerplate: collection_migration ",2021-01-13T09:12:20Z,neutral
759485807,just running rstcheck on that file doesn't yield any errors either.,2021-01-13T14:30:53Z,anger
759489953,"Yeah, whatever",2021-01-13T14:37:26Z,neutral
759570257,"The group_names variable is purposefully alphanumerically sorted by name, and not sorted by definition order. Capital letters, sort before lowercase which is the reason you see them sorted differently between using chg0240322 and CHG0240322 pycon sorted(['c', 'C', 'N']) ['C', 'N', 'c'] If you have further questions please stop by IRC or the mailing list: IRC: on irc.freenode.net mailing list: ",2021-01-13T16:37:16Z,anger
759587936,Can you test with and see if that works as expected?,2021-01-13T17:05:24Z,neutral
759594538,"Can you try this with a more recent version of Ansible? Perhaps Ansible 2.9.x? 2.7 has reached its end of life as of August 2020, and is no longer supported.",2021-01-13T17:16:39Z,neutral
759600232,Splitting PR into two.,2021-01-13T17:26:22Z,neutral
759607973,"The ansible command is provided by the ansiblebase package, and returns the version of the ansiblebase package. See for work being done to clarify that the version is not of the ""ansible"" package. If you have further questions please stop by IRC or the mailing list: IRC: on irc.freenode.net mailing list: ",2021-01-13T17:39:56Z,neutral
759611680,"The test ansibletest sanity test compile python 2.6 [[explain]( failed with 1 error: test/units/module_utils/facts/virtual/test_linux.py46: SyntaxError: 'virtualization_tech_guest': {'bhyve'}, <! job_id: 3987 <! job_id: e6be3969544c83a4eb2976353daa7dc2 <! job_id: None [click here for bot help]( <! boilerplate: shippable_test_result ",2021-01-13T17:46:57Z,fear
759621763," Yes I am always proving seconds so from my perspective your solution would work  I have also tested your patch/merge request , and it seems to work perfectly  ",2021-01-13T18:04:08Z,neutral
759622700," Thanks for added this patch. I have tested it, and it works as expected without having to do anything  Btw, will it be possible to backport this to Ansible 2.10?",2021-01-13T18:05:49Z,neutral
759655716,thanks for reviewing and merging!,2021-01-13T19:06:06Z,joy
759738851,Can you provide the output of the following command: systemctl listunits nopager type service all !component =lib/ansible/modules/service_facts.py,2021-01-13T21:04:45Z,neutral
759892403,"Files identified in the description: lib/ansible/modules/database/mysql/mysql_user.py If these files are incorrect, please update the component name section of the description or use the !component bot command. [click here for bot help]( <! boilerplate: components_banner ",2021-01-14T02:57:10Z,anger
759892406,"Thank you very much for your interest in Ansible. Ansible has migrated much of the content into separate repositories to allow for more rapid, independent development. We are closing this issue/PR because this content has been moved to one or more collection repositories. lib/ansible/modules/database/mysql/mysql_user.py For further information, please see: <! boilerplate: collection_migration ",2021-01-14T02:57:11Z,neutral
759896949,"Thanks for the review, . Can you please add unit tests for this? Will do. I don't see any tests related to role installation...am I starting from scratch, or can you advise? Thanks!",2021-01-14T03:12:35Z,joy
760067049," this is fixed in newer versions. Which is ""newer""? Newer than 2.7? fetch_file is only used if a URL is used, if a key ID is give, it runs aptkey, which does not use the proxy settings... [An easy workaround]( is to just build the URL directly.",2021-01-14T09:18:16Z,fear
760073055,"If you need a way to reproduce this, inspect the logs of the Ansible init container of OAS's wordpresshelm chart prior to commit: ",2021-01-14T09:28:43Z,neutral
760163178,"I just figured out what was wrong : it was the generation of encrypted password, the proper way is: ansiblevault encrypt_string 'my_password' name vault_password while I used in the wrong scenario: ansiblevault encrypt_string stdinname vault_password ",2021-01-14T12:23:11Z,neutral
760188250,"Thank you very much for your interest in Ansible. Ansible has migrated much of the content into separate repositories to allow for more rapid, independent development. We are closing this issue/PR because this content has been moved to one or more collection repositories. lib/ansible/modules/system/locale_gen.py For further information, please see: <! boilerplate: collection_migration ",2021-01-14T13:12:37Z,neutral
760209079,axway Thanks for the help..!! Your workaround resolves the issue we were facing.,2021-01-14T13:51:23Z,joy
760242239,I don't know if I have correctly installed the dev version: I create new venv install requirements.txt git clone source ./hacking/envsetup manually add pr modification on file lib/ansible/module_utils/facts/virtual/linux.py Work fine. PS : how to add your PR in code whitout manually editing ?,2021-01-14T14:46:30Z,sadness
760243834,"That documentation was recently updated about 4 weeks ago, and hasn't been published yet: ",2021-01-14T14:49:05Z,sadness
760283603,The issue author [confirmed]( this works as expected.,2021-01-14T15:50:30Z,joy
760307833,"I thought that too, but the service stops and starts fine. I tailed the log to confirm that. The state query is right after the start. Could i possibly add a delay or something to the query? I also reviewed if anyone else had this problem. Someone else had also reported this but in a older version. The issue never had a resolution as far as i could see and was closed for comments. ",2021-01-14T16:28:38Z,anger
760325287,"All of those directories within the playbooks dir are arbitrary, but named via convention. None of them have any more meaning in a collection than they would in your own ansible project directory where you store playbooks. Additionally: ",2021-01-14T16:56:33Z,fear
760325346,"Files identified in the description: [docs/docsite/rst/dev_guide/developing_collections.rst]( If these files are incorrect, please update the component name section of the description or use the !component bot command. [click here for bot help]( <! boilerplate: components_banner ",2021-01-14T16:56:37Z,anger
760331617,"Thank you very much for your interest in Ansible. Ansible has migrated much of the content into separate repositories to allow for more rapid, independent development. We are closing this issue/PR because this content has been moved to one or more collection repositories. lib/ansible/modules/clustering/k8s/k8s.py For further information, please see: <! boilerplate: collection_migration ",2021-01-14T17:06:43Z,neutral
760350805,thanks!,2021-01-14T17:38:20Z,neutral
760400589," including templates? In my playbook directory it has meaning. Is there any way to have variables relative to the playbooks? e.g. git_url is default to github.com, but can be overwritten via group/host vars in inventory. ",2021-01-14T18:55:12Z,fear
760408304,"I concur, this is not a bug, the machine is unreachable, ansible returns the correct message.",2021-01-14T19:10:15Z,sadness
760408893,doesn't the checksum indicate if the content changed?,2021-01-14T19:11:31Z,neutral
760409178," I don't understand, the machine is online, but ansible can not execute modules on it which is clearly error behavior, not unreachable behavior. To add on to that, ansible itsself is even stating that the device is ""online"" otherwise it wouldn't have moved beyond this statement <testdevice SSH: EXEC ssh vvv o ForwardAgent=yes o ControlPersist=1800s o ControlMaster=auto o StrictHostKeyChecking=no o KbdInteractiveAuthentication=no o PreferredAuthentications=gssapiwithmic,gssapikeyex,hostbased,publickey o PasswordAuthentication=no o 'User=""debian""' o ConnectTimeout=120 o ControlPath=/home/<name/.ansible/cp/8ebc0a9871 testdevice '/bin/sh c '""'""'sudo H S n u root /bin/sh c '""'""'""'""'""'""'""'""'echo BECOMESUCCESSmppcuqjdhlhwljddxlrdzqhwstxudvlg ; /usr/bin/python'""'""'""'""'""'""'""'""' && sleep 0'""'""'' ",2021-01-14T19:12:06Z,anger
760435069,can you reach it via ssh? 'being online' and 'being reachable' are 2 diff things.,2021-01-14T19:46:30Z,neutral
760445416,"Yes. I was also able to execute rm commands, but no creation type commands given the disk full status of the device.",2021-01-14T20:05:17Z,joy
760445720,"Data could not be sent to remote host goes along with the tmp dir being full as you mentioned. And it doesn't fail on earlier tasks because of pipelining, but copy requires a remote tmp dir. If the data cannot be copied to the remote host because the tmp dir is full, it would appear that causes the device to be marked as unreachable.",2021-01-14T20:05:58Z,anger
760451687,doesn't the checksum indicate if the content changed? Content of what?,2021-01-14T20:17:56Z,neutral
760454213," More idempotent way without using command/shell: yaml name: disable default mysql module copy: dest: /etc/dnf/modules.d/mysql.module content: | [mysql] name=mysql stream= profiles= state=disabled when: ansible_os_family == 'RedHat' ansible_distribution_major_version | int = 8 Untested, but think should work too (for MariaDB in this case). yaml name: disable default MariaDB module ini_file: path: /etc/dnf/modules.d/mariadb.module section: mariadb option: state value: disabled no_extra_spaces: yes ",2021-01-14T20:23:03Z,anger
760465699,thanks!,2021-01-14T20:46:11Z,neutral
760494717,Can anyone test with to see if that fixes the issue?,2021-01-14T21:42:45Z,neutral
760499784,"To me, that would constitute an error condition as the actual ssh process did not fail to connect to the device. I would imagine the logic for unreachable would check to see if the ssh connection timed out and if true ""unreachable"" else ...",2021-01-14T21:52:54Z,fear
760501330,"Unfortunately, we just see that SSH cut the connect off during transfer and ssh exited with a 255 which indicates an unknown connection failure. Your debug from SSH actually says it was a timeout.",2021-01-14T21:56:14Z,sadness
760501910,"Ahhh interesting. Limitation of the technology then, I appreciate the info.",2021-01-14T21:57:32Z,joy
760965510,"This isn't the right place to do this, it should really be in the dep resolver. will improve the error by indicating that a concrete artifact pointer wasn't found in addition to giving the expected format for collection names.",2021-01-15T14:14:02Z,anger
760989934,"Thank you very much for your interest in Ansible. Ansible has migrated much of the content into separate repositories to allow for more rapid, independent development. We are closing this issue/PR because this content has been moved to one or more collection repositories. lib/ansible/modules/cloud/amazon/ec2_ami.py For further information, please see: <! boilerplate: collection_migration ",2021-01-15T14:57:39Z,fear
760990189,"The documentation you reference is for installing a role from a git repo. The documentation for installing a collection from a git repo can be found at If you select the collections segment of the docs on the page you reference, it will direct you to the page I linked. If you have further questions please stop by IRC or the mailing list: IRC: on irc.freenode.net mailing list: ",2021-01-15T14:58:04Z,neutral
760999615,"We have added many specific error messages for the ssh issues that are capturable, some sadly will remain as generic as ssh itself does not give enough information. As such I'm going to close this issue and deal with specific messages as they appear.",2021-01-15T15:14:35Z,anger
761002758,"As discussed above, this is a result of running parallel tasks against the same file, ansible does not lock by default so there is a concurrency issue as different processes update the file. Adding serial: 1 at the play level or throttle: 1 at the task level should solve this issue (also mentioned above).",2021-01-15T15:19:51Z,fear
761007848,It appears this issue was actually fixed in the community.general collection: If you have further questions please stop by IRC or the mailing list: IRC: on irc.freenode.net mailing list:,2021-01-15T15:27:55Z,neutral
761009492,"sorry for the delay in responding, but we cannot reproduce this issue. Can you give a simple reproducer example? needs_info",2021-01-15T15:30:40Z,sadness
761017913,have you tried quoting '^Password for \w+': needs_info,2021-01-15T15:44:45Z,neutral
761019190,"closing in favour of , the decrypted extension should really reflect the original file extension, since that is what a decrypted vault is in the end ",2021-01-15T15:46:56Z,neutral
761021410,"I can't reproduce this on 2.9.6 from my test case above, so I guess it's no longer an issue.",2021-01-15T15:50:29Z,fear
761026142,"We continually add platforms, but the fix hould also add a fallback looking for tools (systemd/hostname/etc) if no platform is matched.",2021-01-15T15:58:40Z,neutral
761028644,"closing this for 2 reasons: Though here it is for a specific keyword, we have had the general ask is for adding play keywords for inheritance to import_playbook which is not something we are looking to do at the moment but might reconsider in a future refactoring. The 'gathering' setting already accomplishes what is being asked for here.",2021-01-15T16:03:00Z,neutral
761039810,note: paths we might want to keep as bytes.,2021-01-15T16:22:25Z,neutral
761042755,"Files identified in the description: lib/ansible/plugins/inventory/gcp_compute.py If these files are incorrect, please update the component name section of the description or use the !component bot command. [click here for bot help]( <! boilerplate: components_banner ",2021-01-15T16:27:49Z,anger
761117432,Do we want to load antsibull in 2.9? The 2.9 docs don't use it . . .,2021-01-15T18:46:12Z,neutral
761118554,Same question here as on . Do we need/want antsibull on the old stable branches?,2021-01-15T18:48:24Z,neutral
761178560," for some reason, the sanity test is still using Sphinx v1.7.9.",2021-01-15T20:23:06Z,fear
761813710,"[This answer]( on a 2016 StackOverflow question has a good explanation on possible root cause of the issue, that might be helpful to anyone working a permanent fix. Also and its comments might be worth reading. Some workarounds, depending on the use case: ignore_errors: true register: file_deleted retries: X until: file_deleted is success If the file is blocked by a running process, define a task with wait_for: <path to pid timeout: N ",2021-01-17T13:35:12Z,neutral
761835638,Hi what about using the no_log option in the playbook header? Regards,2021-01-17T16:04:35Z,neutral
761888923,"The example playbook was successful for me in 2.9 (see [future comment]( but failed in devel. Note: when successful, output is large from ansible.com, I used this for easier reading: yaml hosts: localhost tasks: debug: msg: ""{{ lookup('url', ' }}"" vars: ansible_lookup_url_timeout: ""{{ 1 + 1 }}"" Also I thought it might've been a difference between Jinja2 native setting or not. Running with ANSIBLE_JINJA2_NATIVE=true did not work in devel either though.",2021-01-17T22:09:14Z,joy
761902721,"Ok, so I wrote a little script to go back and try the test playbook on every commit in devel, going back in time, to try to see where it changed, and the results are disappointing. In short, it ""works"" in 2.9 because there is no vars entry in 2.9; it was added in this commit: Guess I could've found that out more easily just looking at the 2.9 docs 🤦‍♂️",2021-01-17T23:50:40Z,sadness
761982764,"This error is probable due to the playbook being run in an AWX container, and groups available on the host OS are not available in the container. :O Will do some more testing and report back.",2021-01-18T05:07:16Z,neutral
762196248,"By defining that group in the AWX container as well it works fine. This is not a bug. name: Ensure group ""webhook"" exists group: name: webhook state: present ",2021-01-18T11:44:18Z,joy
762309086,"You are using naming conventions of a role, but are not actually using a role. As such, ansible has no idea to look in the handlers directory. You will need to restructure your files to accommodate this functionality. Please stop by IRC or the mailing list for help in how to achieve your goal: IRC: on irc.freenode.net mailing list: ",2021-01-18T15:10:19Z,neutral
762316077,Bug in Launchpad is still waiting to be solved in Ubuntu 20.04. As bug seems to be fixed in 20.10 I think that version should be already supported and wait for Ubuntu 20.04. ![image](,2021-01-18T15:22:09Z,fear
762317229," well spotted, I made that mistake a long time ago in group_vars/all/ and I would not have thought about this honestly. Thanks.",2021-01-18T15:24:06Z,sadness
762322559,I agree. IMHO there is no reason to not support Ubuntu 20.10 if the bug is fixed on it.,2021-01-18T15:33:32Z,neutral
762398281,"Files identified in the description: lib/ansible/plugins/filter/ipaddr.py If these files are incorrect, please update the component name section of the description or use the !component bot command. [click here for bot help]( <! boilerplate: components_banner ",2021-01-18T18:01:23Z,anger
762398285,"Thank you very much for your interest in Ansible. Ansible has migrated much of the content into separate repositories to allow for more rapid, independent development. We are closing this issue/PR because this content has been moved to one or more collection repositories. lib/ansible/plugins/filter/ipaddr.py For further information, please see: <! boilerplate: collection_migration ",2021-01-18T18:01:24Z,neutral
762399355,"I'm guessing this is something that may be specific to the Ubuntu FIPS 1402 implementation. Unfortunately, to get access to FIPS support on Ubuntu, you have to purchase Ubuntu Advantage. I've not found a way to download the NSX Edge appliance either.",2021-01-18T18:03:51Z,anger
762400418,"Thank you very much for your interest in Ansible. Ansible has migrated much of the content into separate repositories to allow for more rapid, independent development. We are closing this issue/PR because this content has been moved to one or more collection repositories. lib/ansible/plugins/lookup/filetree.py For further information, please see: <! boilerplate: collection_migration ",2021-01-18T18:06:19Z,neutral
762400717,Closing in favor of,2021-01-18T18:06:58Z,neutral
762403141," the format of the doc also has a mistake. That is not a mistake, that is valid YAML. List indicators do not need to be indented past their parent.",2021-01-18T18:12:43Z,sadness
762404847,See also I think likely just needs to be closed.,2021-01-18T18:16:26Z,neutral
762410402,We already have an isidentifier function in ansible. Located at ansible.utils.vars.isidentifier,2021-01-18T18:28:50Z,fear
762413332,"ok, but how about the parameter type issue above?",2021-01-18T18:36:13Z,joy
762425928,We already have an isidentifier function in ansible. Located at ansible.utils.vars.isidentifier I've taken a prompt look and it seems that this helper doesn't replicate the stdlib behavior so I'm not sure if we want to reuse it for FQCNs.,2021-01-18T19:08:24Z,anger
762434516,"Just as an FYI, I tried this change locally and it looks like it requires the plugin to call set_options() before the deprecation message will appear. Many of our builtin plugins (e.g., file) do not call that method since it doesn't seem to be required to do so.",2021-01-18T19:29:32Z,anger
762444669,thanks for reviewing and merging!,2021-01-18T19:56:24Z,joy
762446246,"Seems you can get 3 lic for free [source]( Anyone can use UA Infrastructure Essential for free on up to 3 machines (limitations apply). All you need is an Ubuntu One account. And if you’re a recognised Ubuntu community member, it’s free on up to 50 machines.",2021-01-18T20:00:35Z,neutral
762454567,Thanks for the Ansible documentation fix!,2021-01-18T20:21:59Z,joy
762456871,"Actually, whatever type you use for msg is just parroted back in the return, so it may be more than just list. Example as also valid: yaml tasks: debug: msg: something: ""else"" also: 5 If anything, type should be complex maybe?",2021-01-18T20:27:46Z,neutral
762458811,Probably raw,2021-01-18T20:33:03Z,neutral
762459230,"no, its still a string, the issue is that 'anything passed' gets converted into a string representation of itself, so lists and dictionaries become the 'string version' of themselves.",2021-01-18T20:34:10Z,fear
762460386,"the text is still not correct, the 'ansible_become_' vars are not AUTOMATICALLY populated, but if you set them in any way vars can be set (not the same as using cli options, keywords or configuration) they are still there ansible m debug a 'msg={{ansible_become_password}}' e ansible_become_password=test2 localhost localhost | SUCCESS = { ""msg"": ""test2"" } vs ansible m debug a 'msg={{ansible_become_password}}' K localhost BECOME password: localhost | FAILED! = { ""msg"": ""The task includes an option with an undefined variable. The error was: 'ansible_become_password' is undefined. 'ansible_become_password' is undefined"" } ",2021-01-18T20:37:21Z,fear
762460411,"This should be easy to add. Just need to add a ca_path argument, and pass it on to fetch_url.",2021-01-18T20:37:27Z,anger
762478259,"As of now, when using vars: on a role definition, this is the expected behavior. vars: are scoped at the play level, and the last one defined wins. When roles are encountered during playbook parsing time, they are automatically merged into the play. Switching to role params instead, produces: bar, bar, cat, cat a/meta/main.yml: yaml dependencies: role: dep foo: bar b/meta/main.yml yaml dependencies: role: dep foo: cat If you have further questions please stop by IRC or the mailing list: IRC: on irc.freenode.net mailing list: ",2021-01-18T21:28:06Z,fear
762481207,"Currently the actual precedence is: 14. role vars (defined in vars:) 15. role vars (defined in role/vars/main.yml) 16. block vars (only for tasks in block) 17. task vars (only for the task, excluding vars: on roles) I think honestly, vars: should probably override role/vars/main.yml. I cannot imagine anyone would be relying on the current behavior, unless they don't realize thier vars: aren't doing what they anticipated. This would require a change in Role.get_vars to swap those 2 lines.",2021-01-18T21:37:07Z,fear
762491411," Unfortunately, that's expected. That's the position we get from YAML. Since it's an ""end of stream"" error, the error address is effectively the last line and column of the file. I'm not sure how we would go about getting the ""correct"" position in this situtaion. ",2021-01-18T22:10:22Z,sadness
762499609,"Looking at your play again, I see those tasks are 1 after another. You might be able to add a pause task in between. The big thing with many service managers, is that they don't wait to ensure that service fully started. So after telling a service to start, it may take some amount of time afterwards before it fully starts. Maybe you can put an until on the service_facts to wait until the service is actually started. needs_info",2021-01-18T22:38:09Z,neutral
762501805,Is this even still an issue since was merged?,2021-01-18T22:46:54Z,neutral
762503650,Thanks for the ping. I've commented on the PR.,2021-01-18T22:54:03Z,joy
762513012,Good find,2021-01-18T23:31:01Z,neutral
762682335,"Files identified in the description: [lib/ansible/modules/yum.py]( If these files are incorrect, please update the component name section of the description or use the !component bot command. [click here for bot help]( <! boilerplate: components_banner ",2021-01-19T08:25:18Z,anger
762695661,closed. will use module instead.,2021-01-19T08:50:53Z,neutral
762783663,I just ran into this exact issue. Is there a specific reason why this merge conflict hasn't been resolved since almost a year?,2021-01-19T11:31:08Z,anger
762798859,"Files identified in the description: [lib/ansible/modules/template.py]( [lib/ansible/plugins/lookup/vars.py]( lib/ansible/template [lib/ansible/vars/hostvars.py]( If these files are incorrect, please update the component name section of the description or use the !component bot command. [click here for bot help]( <! boilerplate: components_banner ",2021-01-19T12:03:27Z,anger
762808820,Duplicate of,2021-01-19T12:24:52Z,neutral
762829014," ... Looking at the module, option ""disabled"" is already in place but only affects lines in files (prefixing lines with a ). It seems feasible to have the ""disabled"" option affect the filename when used in combination with option ""filename"" I used the cron module functionality as it previously worked in v2.9.x. After updating to v2.10.5, my crontab file was removed when just one line should have been removed. I found the comments in this issue and adjusted my playbook and roles as such but it would be good to mention this in the documentation as well: ",2021-01-19T13:08:31Z,anger
762843378,"Hey, I noticed this issue still occurs on Ansible 2.10.5. What's required to get PR merged? Workaround: shell mv skeleton/.git skeleton/.git.not ansiblegalaxy init roleskeleton=skeleton MY_ROLE Role MY_ROLE was created successfully mv skeleton/.git.not/ skeleton/.git ",2021-01-19T13:36:37Z,fear
762878374,created by mistake,2021-01-19T14:32:56Z,sadness
762879403,"It's a pattern that would be easy to mistakenly change again, so it's waiting on a test. Anyone who has time should feel free to cherrypick the initial work to keep attribution and open a new PR with a test, since it appears the original author may not be interested in working on it anymore.",2021-01-19T14:34:31Z,anger
762903888,We will need a changelog and tests before we consider merging this. We may also want to bikeshed on the headers_secret name.,2021-01-19T15:10:05Z,neutral
762910435,Thanks! I tested this and seems to work as expected. We will need some tests for this. There are existing unit tests you could use/modify to make sure that display.prompt() is being called with the expected arguments.,2021-01-19T15:19:14Z,neutral
762914716,"This will subsume if merged, so we should close that one at that point.",2021-01-19T15:25:10Z,sadness
762914722,"This is happening because ncurses is available in the Emacs shell buffer but ncurses.tigetstr() is returning None which is quite odd. The fix is pretty simple. patch diff git lib/ansible/plugins/action/pause.py lib/ansible/plugins/action/pause.py index 88babe61b3..7a149c6621 100644 lib/ansible/plugins/action/pause.py +++ lib/ansible/plugins/action/pause.py @@ 51,8 +51,9 @@ except ImportError: HAS_CURSES = False if HAS_CURSES: MOVE_TO_BOL = curses.tigetstr('cr') CLEAR_TO_EOL = curses.tigetstr('el') + In case curses.tigetstr() returns None + MOVE_TO_BOL = curses.tigetstr('cr') or b'\r' + CLEAR_TO_EOL = curses.tigetstr('el') or b'\x1b[K' else: MOVE_TO_BOL = b'\r' CLEAR_TO_EOL = b'\x1b[K' Testing this will most likely required creating a unit test to mock the curses.tigetstr() calls.",2021-01-19T15:25:11Z,fear
762920342,"Discussed this in triage. The type: str here actually means that what is passed in will be converted to str, if possible, otherwise then you'll get an error. Given that, closing per above.",2021-01-19T15:33:04Z,fear
762924739,Closing per above.,2021-01-19T15:39:37Z,neutral
762928811,Tests and changelog.,2021-01-19T15:45:28Z,neutral
762959796,"Files identified in the description: None If these files are incorrect, please update the component name section of the description or use the !component bot command. [click here for bot help]( <! boilerplate: components_banner ",2021-01-19T16:30:09Z,anger
762963338,fyi,2021-01-19T16:35:13Z,neutral
762965426,This issue is waiting for your response. Please respond or the issue will be closed. [click here for bot help]( <! boilerplate: needs_info_base,2021-01-19T16:38:26Z,neutral
762972648,Ansible version: 2.9.14 Problematic Component: Ansible facts,2021-01-19T16:49:18Z,fear
762994772,I got intrigued a bit and looked into this and it does indeed seem that bash [uses temp files]( for heredocs if the size of the heredoc is larger than F_SETPIPE_SZ.,2021-01-19T17:23:06Z,anger
763016267,"Would this be preferable to avoid the repeated constants? patch diff u pause.py.orig pause.py pause.py.orig 20210119 1235.000000000 0500 +++ pause.py 20210119 1234.000000000 0500 @@ 46,12 +46,12 @@ except ImportError: HAS_CURSES = False +MOVE_TO_BOL = b'\r' +CLEAR_TO_EOL = b'\x1b[K' if HAS_CURSES: MOVE_TO_BOL = curses.tigetstr('cr') CLEAR_TO_EOL = curses.tigetstr('el') else: MOVE_TO_BOL = b'\r' CLEAR_TO_EOL = b'\x1b[K' + In case curses.tigetstr() returns None + MOVE_TO_BOL = curses.tigetstr('cr') or MOVE_TO_BOL + CLEAR_TO_EOL = curses.tigetstr('el') or CLEAR_TO_EOL class AnsibleTimeoutExceeded(Exception): ",2021-01-19T17:57:20Z,fear
763060672,"Just saw this mentioned in core meeting, could be a possible solution? ",2021-01-19T19:06:08Z,joy
763085889,"Missing selinux Python library indicates that libselinuxpython is not installed for the python interpreter that is being invoked on that remote host. On node2, if you ssh in, and run the following, it is effectively what ansible does: /usr/bin/python c 'import selinux' ",2021-01-19T19:46:48Z,fear
763096804,"no, this would , thought it might also need that one for 'hostvars'",2021-01-19T20:06:56Z,sadness
763099548," Now this implementation does make the variable composition dependent upon evaluation order, but as python preserves order of dictionary keys, there shouldn't be any issues as long as the user defines them in the correct order. That feature is python version dependant",2021-01-19T20:12:08Z,fear
763102122,"You're right, 3.7. I could have sworn that feature was older, like 3.0, but it seems not :( I will investigate an alternate solution.",2021-01-19T20:15:15Z,fear
763108217,"Files identified in the description: None If these files are incorrect, please update the component name section of the description or use the !component bot command. [click here for bot help]( <! boilerplate: components_banner ",2021-01-19T20:21:36Z,anger
763152174,"I can not reproduce this with currently supported versions of Ansible. TASK [search for pools] ok: [localhost] = (item={'key': 'Testpool', 'value': {'member': [{'address': 'host1', 'port': 23101}, {'address': 'host2', 'port': 23101}]}}) = {""ansible_facts"": {""matched_pool"": ""Testpool""}, ""ansible_loop_var"": ""search_pool_item"", ""changed"": false, ""search_pool_item"": {""key"": ""Testpool"", ""value"": {""member"": [{""address"": ""host1"", ""port"": 23101}, {""address"": ""host2"", ""port"": 23101}]}}} If you are still having problems, feel free to open a new issue with a complete reproducer. If you have further questions please stop by IRC or the mailing list: IRC: on irc.freenode.net mailing list: ",2021-01-19T21:27:10Z,joy
763159768,"Files identified in the description: None If these files are incorrect, please update the component name section of the description or use the !component bot command. [click here for bot help]( <! boilerplate: components_banner ",2021-01-19T21:42:16Z,anger
763163546,"That last output shows that libselinuxpython is present, and selinux is enforcing. What is the problem with the EL6 nodes?",2021-01-19T21:49:19Z,neutral
763164472,The test ansibletest sanity test docsbuild [[explain]( failed with 1 error: docs/docsite/rst/collections/ansible/builtin/expect_module.rst0: warning: Inline literal startstring without endstring. <! job_id: 4435 <! job_id: b4360131025f7751fb003475e2eb97a7 <! job_id: None [click here for bot help]( <! boilerplate: shippable_test_result,2021-01-19T21:51:04Z,fear
763171085,"The error Failed to get information on remote file happens when ansible cannot stat a file. That appears to be happening on the template task, before the task does anything else. The stat is one of the very first things that happens.",2021-01-19T22:04:21Z,fear
763172193,"that makes sense...when using template files, does the ansible host first copy the file to a tmp location on the node...then copy from the tmp location to the target destination? I am trying to understand how to troubleshoot this on the specific hosts that are failing. This same playbook works properly on over 30 50 hosts and fails only on about a dozen.",2021-01-19T22:06:30Z,neutral
763174064,This will also require tests and a changelog entry.,2021-01-19T22:10:34Z,neutral
763181643,"Ansible will copy the file to a temp location on the node, and then move the file to the indicated dest. But it seems like the file exists, but cannot be stat by the remote user.",2021-01-19T22:26:38Z,fear
763187600,Thanks....sometimes just need someone else prodding me. The issue is the ansible user running the playbooks does not have sudo on the set of RHEL6 hosts it is failing on. Simple issues like that are the easiest thing to overlook. Please go ahead and close this issue as keyboard driver is failing. :),2021-01-19T22:36:10Z,neutral
763188969,Closing per above.,2021-01-19T22:39:21Z,neutral
763198297,The test ansibletest sanity test packagedata [[explain]( failed with 2 errors: docs/docsite/core_rst/installation_guide/index.rst0: File was not added to sdist docs/docsite/core_rst/installation_guide/intro_configuration.rst0: File was not added to sdist <! job_id: 4440 <! job_id: 3314adef377c33cf5fe825b75534b100 <! job_id: None [click here for bot help]( <! boilerplate: shippable_test_result,2021-01-19T23:02:10Z,fear
763261304," Thanks! I tested this and seems to work as expected. We will need some tests for this. There are existing unit tests you could use/modify to make sure that display.prompt() is being called with the expected arguments. Thanks, I've added a unit test.",2021-01-20T01:29:14Z,joy
763279642," Actually, it appears that ""preserve"" is the default behaviour if mode isn't specified. Do user/group ownerships also left intact?",2021-01-20T02:14:20Z,anger
763310276,Perhaps an easier workaround? command: cmd: dnf configmanager addrepo (url) warn: false args: creates: /etc/yum.repos.d/(something).repo,2021-01-20T03:48:29Z,fear
763348655," aware, these will go into the next rc1.",2021-01-20T05:41:05Z,neutral
763349109,Thanks for the information,2021-01-20T05:42:12Z,joy
763354540,resolved_by_pr,2021-01-20T05:55:06Z,neutral
763355421,Could you please check if PR and let me know if it works for you? Thanks.,2021-01-20T05:56:54Z,neutral
763409094,I think the no_log option in the playbook header results in the whole task to be not logged. It is a problem for us as we miss many logs. My request is to have only the token in the request header to be obliterated.,2021-01-20T07:51:54Z,fear
763512385,"Thank you very much for your interest in Ansible. Ansible has migrated much of the content into separate repositories to allow for more rapid, independent development. We are closing this issue/PR because this content has been moved to one or more collection repositories. lib/ansible/modules/storage/netapp/na_ontap_service_processor_network.py For further information, please see: <! boilerplate: collection_migration ",2021-01-20T10:41:18Z,neutral
763547046,I got intrigued a bit and looked into this and it does indeed seem that bash [uses temp files]( for heredocs if the size of the heredoc is larger than F_SETPIPE_SZ. Thank you very much for verifying that :),2021-01-20T11:42:41Z,anger
763573931,"I don't know if the cause is the same but I'm seeing a similar issue with loops wrapped into false conditionals (which should be just ignored), here is an example which fails on Ansible 2.7, 2.8 and 2.10 (python3): $ cat test.j2 {% if false %} {% for arg in args if false %} text {% endfor %} {% endif %} $ cat play.yml hosts: localhost gather_facts: no vars: args: ""{{ myvar }}"" tasks: template: src: test.j2 dest: test $ ansibleplaybook play.yml fatal: [localhost]: FAILED! = {""changed"": false, ""msg"": ""AnsibleUndefinedVariable: ['{{ myvar }}']: 'myvar' is undefined""} ",2021-01-20T12:29:38Z,fear
763590228,recheck,2021-01-20T12:59:54Z,neutral
763647774,I was wondering if this feature was going to make it into the 2.11 release?,2021-01-20T14:35:20Z,neutral
763707490,fixed via and included in 2.8 and newer versions.,2021-01-20T15:24:29Z,fear
763708802,"Note: the issue with this PR as is is that it doesn't amend the changed in the overall task result after the loop ended, just the per iteration results.",2021-01-20T15:26:35Z,sadness
763771507,"Files identified in the description: None If these files are incorrect, please update the component name section of the description or use the !component bot command. [click here for bot help]( <! boilerplate: components_banner ",2021-01-20T16:38:34Z,anger
763777188,closing via alternate,2021-01-20T16:46:43Z,neutral
763777432,"Files identified in the description: [lib/ansible/plugins/become/sudo.py]( If these files are incorrect, please update the component name section of the description or use the !component bot command. [click here for bot help]( <! boilerplate: components_banner ",2021-01-20T16:47:07Z,anger
763833946,Thank you !,2021-01-20T18:09:56Z,neutral
763838483,Thanks for the quick merge!,2021-01-20T18:17:41Z,joy
763839949,I hit this issue running Ansible from Microsoft Azure DevOps' Ansible module. Thanks so much for the patch!,2021-01-20T18:20:09Z,joy
763840574,I hit this issue running Ansible from Microsoft Azure DevOps' Ansible module. Thanks so much for the patch! (AzDevOps' Ansible module interprets any output to stderr as a failure by default.),2021-01-20T18:21:17Z,joy
763853064,The test ansibletest sanity test pep8 [[explain]( failed with 1 error: lib/ansible/playbook/play.py5: E303: too many blank lines (2) <! job_id: 4493 <! job_id: 9c78dcf9c3fd7711bbfbd6a5dfde73ce <! job_id: None [click here for bot help]( <! boilerplate: shippable_test_result,2021-01-20T18:42:26Z,fear
763866506,can we get the tower_blocker label put on this issue?,2021-01-20T19:05:33Z,neutral
763871754,TODO: add a change fragment,2021-01-20T19:15:17Z,neutral
763873339,You're welcome !,2021-01-20T19:18:15Z,joy
763903091,"This is largely already resolved. In we fixed the unsafe_writes fallback, so that the exception you mention no longer happens. This would however require you to add unsafe_writes: true to all tasks where this could happen. In we are adding support for the ANSIBLE_UNSAFE_WRITES env var to be set on targets, that will auto use unsafe_writes for all modules that implement it.",2021-01-20T20:11:27Z,neutral
763938619,"I think that it is considered an unacceptable workaround for tower/awx users to have to do this on all their content that used to work This would however require you to add unsafe_writes: true to all tasks where this could happen. we're concerned that setting this globally is too broad In we are adding support for the ANSIBLE_UNSAFE_WRITES env var to be set on targets, that will auto use unsafe_writes for all modules that implement it. and that we need a way that does not affect EVERY host, just actions locally in the container",2021-01-20T20:58:12Z,fear
763942104,"You would likely want this to be dictated by the target host. In the example of localhost, and targeting localhost, you would do something like: $ ANSIBLE_UNSAFE_WRITES=1 ansibleplaybook ... This would only impact localhost, and not affect all hosts. It's not a config entry, it's a fallback that modules will use for the unsafe_writes module argument, so it has to be set on the target. There are several ways to do it, such as the environment: keyword also, and setting 0 or 1 based on whether or not the host needs it. ",2021-01-20T21:00:23Z,neutral
763948049,"So in an execution environment, an ENV ANSIBLE_UNSAFE_WRITES=1 could be set in the Containerfile/Dockerfile which would be used for all file modules supporting unsafe_writes that target localhost only.",2021-01-20T21:09:38Z,anger
763953398,"| Hypothetically, the module could detect what volume the destination is in, and use a tmp stage file in that volume. This is already the case, the file is copied to tmp location in same volume if the initial rename didn't work, unsafe_writes ONLY comes into play if all other attempts to atomically update the file failed.",2021-01-20T21:19:28Z,sadness
763984579,The test ansibletest sanity test pep8 [[explain]( failed with 1 error: lib/ansible/playbook/block.py13: E722: do not use bare 'except' <! job_id: 4513 <! job_id: 8629df12a5b76ecd2202ee9fe55ff5de <! job_id: None [click here for bot help]( <! boilerplate: shippable_test_result,2021-01-20T22:13:46Z,fear
764027104,Hopefully FreeBSD 11.4 will work reliably now that switched our instances over from c4.large to c5.large.,2021-01-20T23:34:09Z,fear
764195881,Sorry for the trouble. Reposted the issue on the collection repository,2021-01-21T02:47:08Z,sadness
764235463,If the apt or yum repo could not work. the client will hang too.,2021-01-21T04:08:02Z,neutral
764398028,"Files identified in the description: [lib/ansible/playbook/task.py]( If these files are incorrect, please update the component name section of the description or use the !component bot command. [click here for bot help]( <! boilerplate: components_banner ",2021-01-21T05:52:16Z,anger
764417443,"This is still an issue. Running into this testing against CentOS 8 on docker through molecule. Would love to use this, but I have to add nonidempotent tasks that formats an absolute path just for this module to work. If I use the path provided by stat/file/copy/get_url returns, this module just keeps throwing this error if the tarball isn't at root. It really doesn't like extracting a .tar.gz if it lives anywhere off of / and not using an absolute path, for whatever reason.",2021-01-21T06:38:21Z,fear
764487612,Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to Please resubmit this issue in the above repository. If you have further questions please stop by IRC or the mailing list: IRC: on irc.freenode.net mailing list:,2021-01-21T09:02:26Z,neutral
764491152,Thanks for your fast response!,2021-01-21T09:08:40Z,joy
764522580,"Files identified in the description: [lib/ansible/modules/replace.py]( If these files are incorrect, please update the component name section of the description or use the !component bot command. [click here for bot help]( <! boilerplate: components_banner ",2021-01-21T10:02:54Z,anger
764526507,I think this is already mentioned [Defining variables at runtime]( So can we close this issue?,2021-01-21T10:09:28Z,sadness
764530905,"This is not a bug. What happens is that yaml replace: '\1{{ bbb_presentation_max_size }}\2' is templated to yaml replace: '\1100m\2' which means that it is effectively using back reference of \1100. You need to somehow separate the back reference and the subsequent number, for example like so: yaml hosts: localhost gather_facts: no tasks: name: Set max size of presentation uploads replace: path: 73316.txt regexp: '^(\s+ Allow 30M uploaded presentation document.\n\s+client_max_body_size\s)\w+(;)$' replace: '\g<1{{ bbb_presentation_max_size }}\2' vars: bbb_presentation_max_size: 100m User questions are better suited for either the mailing list or the IRC channel: IRC: on irc.freenode.net mailing list: ",2021-01-21T10:17:13Z,neutral
764578824,"Files identified in the description: [lib/ansible/modules/ping.py]( If these files are incorrect, please update the component name section of the description or use the !component bot command. [click here for bot help]( <! boilerplate: components_banner ",2021-01-21T11:32:13Z,anger
764625932," Thank you very much for your quick support. Since, at least as I see it, this behavior is far from obvious I would find it appropriate to mention it in the docs.",2021-01-21T12:58:43Z,neutral
764658646," is this bug report abandoned? I'm still seeing this problem on Ansible 2.9.9 and none of the suggested workarounds have any effect. If using a BastionHost, have you tried this ",2021-01-21T13:55:20Z,fear
764673546," I updated the test, could you please take a look?",2021-01-21T14:19:22Z,neutral
764708054,This is on my list. I haven't forgotten about it but am just working on other things at the moment.,2021-01-21T15:08:05Z,sadness
764710938,"[Update] After I remove the password from my private key, everything starts to work fine I recheck and with password on my private key Ansible prompt few times to enter the password and then fails So, it looks like nothing to do with 'ping' module, but more if the password is set on ssh private key",2021-01-21T15:12:15Z,neutral
764719903," Yup, that looks good.",2021-01-21T15:25:05Z,joy
764731674,"looks like it, thanks!",2021-01-21T15:41:53Z,joy
764809913,This looks like a failure to update the apt cache. Cache update retrying was added in . Please try with Ansible 2.10 and see if that resolves the issue. needs_info,2021-01-21T17:24:55Z,sadness
764860805," I'd like to see the addition of mypy as a sanity test done in a separate PR, so we can focus on the galaxy changes first. No problem. I just needed it here during development. Here you go: I think I've addressed all your requests now.",2021-01-21T18:50:07Z,anger
764862743,"Files identified in the description: lib/ansible/modules/files/synchronize.py If these files are incorrect, please update the component name section of the description or use the !component bot command. [click here for bot help]( <! boilerplate: components_banner ",2021-01-21T18:53:37Z,anger
764862748,"Thank you very much for your interest in Ansible. Ansible has migrated much of the content into separate repositories to allow for more rapid, independent development. We are closing this issue/PR because this content has been moved to one or more collection repositories. lib/ansible/modules/files/synchronize.py For further information, please see: <! boilerplate: collection_migration ",2021-01-21T18:53:38Z,neutral
764867971,"Files identified in the description: None If these files are incorrect, please update the component name section of the description or use the !component bot command. [click here for bot help]( <! boilerplate: components_banner ",2021-01-21T19:02:32Z,anger
764872628,"We should probably document this in one place and share it since it applies to ansibleplaybook, ansibleconsole, etc.",2021-01-21T19:11:11Z,neutral
764877184,"This is working as expected. Not all operations are idempotent. You could use the cache_valid_time option to control when it's updated. If you want to contribute this as a feature though, it isn't something we'd oppose.",2021-01-21T19:19:12Z,neutral
764886935,"We don't have plans to add this, but there are a few ways you could do this already (such as via a custom connection plugin or loading the file and using it to populate the environment keyword).",2021-01-21T19:35:08Z,neutral
764891735,We think a simpler approach is to partition the playbook instead of handling this logically. We've had similar discussions for roles and rejected the feature. You could also handle this via your execution environment (such as via tower jobs or a shell script).,2021-01-21T19:43:36Z,neutral
764893291,Can you provide a complete example of how to trigger this? Thanks.,2021-01-21T19:46:16Z,joy
764910134,"A fix has been mentioned for 2.9.11, but it appears this is still open. Is there a fix still expected for this?",2021-01-21T20:16:14Z,fear
764917756,Nobody would mind against a [draft PR]( Everybody could be hit be a bus with COVID patients.,2021-01-21T20:29:58Z,fear
764919672,OK. I can sympathize with this and I've googled around to see how people have gone about this and I can't say I was particularly pleased with how that looks but I'll try.,2021-01-21T20:33:43Z,joy
764920398," Is there a fix still expected for this? Yes, however a lot of testing needs to be done on any solution we come up with, to ensure whatever change we make, does not cause other issues. The fix mentioned in this issue has been rules out as it doesn't fully address the issues. Although this issue does affect some collections, there are workarounds collection authors can make to not run into this issue (See all of the commits for other repos above) Once we understand the best way to resolve the issue from our side, we'll submit a fix.",2021-01-21T20:35:17Z,fear
764942641,"If I install this branch in an empty docker container and run ansiblegalaxy collection install community.network ansiblegalaxy collection verify community.network the second fails with ERROR! Error when getting collection version metadata for community.network: from default ( (HTTP Code: 404, Message: Not found. Code: not_found) ",2021-01-21T21:08:11Z,anger
764969034,see delegate_facts:,2021-01-21T22:00:55Z,neutral
764970404,This PR was evaluated as a potentially problematic PR for the following reasons: More than 50 changed files. Such PR can only be merged by human. Contact a Core team member to review this PR on IRC: devel on irc.freenode.net [click here for bot help]( <! boilerplate: bad_pr,2021-01-21T22:03:43Z,fear
765028337,Woah! That's unexpected. I guess we need more integration tests. Thanks for reporting! Is that under Python 2?,2021-01-22T00:26:13Z,joy
765030022,"Fix for the first one would be diff diff git a/lib/ansible/galaxy/collection/__init__.py b/lib/ansible/galaxy/collection/__init__.py index 641e88e1d5a..21e09503fdf 100644 a/lib/ansible/galaxy/collection/__init__.py +++ b/lib/ansible/galaxy/collection/__init__.py @@ 623,7 +623,7 @@ def verify_collections( raise AnsibleError(message='Collection %s is not installed in any of the collection paths.' % collection.fqcn) remote_collection = Candidate( collection.fqcn, collection.ver, + local_collection.fqcn, local_collection.ver, None, 'galaxy', ) ",2021-01-22T00:30:38Z,neutral
765073348,"Files identified in the description: None If these files are incorrect, please update the component name section of the description or use the !component bot command. [click here for bot help]( <! boilerplate: components_banner ",2021-01-22T02:36:56Z,anger
765138082,it's all under Python 3.8 (docker container) and 3.9 (my system). I'll try to debug the list issue.,2021-01-22T05:38:25Z,fear
765233086,Thanks to the one with the glasses!,2021-01-22T08:31:33Z,joy
765258368,I don't have the problem anymore. I have upgraded ansible to 2.10 using pip3 to use python3 instead of python2,2021-01-22T09:15:11Z,neutral
765336229,"Just to be sure about the future; linked to: this commit the issue this exchange (Ubuntu 20.04 vs 20.10) the fact that only new ansible release published on PPA include new OS distribution if not existing previously What is the synthesis matrix of what will be published on ? Ansible version (2.10 / 2.11) Ubuntu version (20.04 focal / 20.10 groovy) Estimated roadmap (no engagement for sure, probably linked to [ansible 2.11 roadmap]( it is just to have an idea) Many thanks in advance",2021-01-22T11:26:01Z,neutral
765415205," Can you provide a complete example of how to trigger this? Thanks. Hi hertel, This line triggers the exception. The exception: ",2021-01-22T13:56:42Z,joy
765427437,"I'll be damned. Thanks . Just needed: set_fact: use_ansible_connection: ""{{ (whoami_control_machine_output.stdout == 'awx') | ternary('ssh','local') }}"" delegate_to: localhost delegate_facts: yes And then use it as above: ansible_connection: ""{{ hostvars['localhost']['use_ansible_connection'] }}"" I tested this workaround successfully in 2.9.17 and 2.10.5.",2021-01-22T14:13:45Z,anger
765459075,Thanks for taking a look . Too many cooks in the kitchen this will be consolidated with,2021-01-22T14:54:55Z,joy
765468575,"Sorry for the delayed response. As noted above, this is a configuration issue. We don't plan to make the module silently succeed or try to detect if we're running in a container, but you can handle this in the playbook with failed_when. You could also use a conditional on your hostname tasks like when: ansible_facts.virtualization_type not in ('docker', 'container', 'containerd').",2021-01-22T15:06:58Z,sadness
765469857,This has been resolved by and there should be a more informative error message.,2021-01-22T15:08:49Z,fear
765475486,"Since there are only a couple issues open, we'll handle the rest as individual tickets.",2021-01-22T15:16:10Z,neutral
765478770,We discussed this in backlog today and don't plan on adding this because existing build systems already handle more than we want to include in ansiblegalaxy.,2021-01-22T15:20:21Z,anger
765480843,Closing as a duplicate of .,2021-01-22T15:23:01Z,neutral
765484064,"The error message indicates the solution: Hint: If you passed a list/dict of just one element, try adding wantlist=True to your lookup invocation or use q/query instead of lookup. So either use: loop: ""{{ lookup('dict', users, wantlist=True) }}"" or loop: ""{{ q('dict', users) }}"" Or more preferably, don't use lookup at all, and use the dict2items filter: loop: ""{{ users | dict2items }}"" If you have further questions please stop by IRC or the mailing list: IRC: on irc.freenode.net mailing list: ",2021-01-22T15:27:50Z,anger
765490094,This looks like it may be a duplicate of,2021-01-22T15:36:02Z,joy
765494918,Sorry for the delayed response. There isn't enough information to reproduce this with the task provided. Can you provide a complete reproducer as well as the complete output of your task (with vvvv) when it fails? needs_info,2021-01-22T15:42:30Z,sadness
765497715,"It looks like metadata is necessary to remove an existing role with force, but since a role isn't required to have metadata we should probably fix this. there's a forcewithdeps flag for installing dependencies",2021-01-22T15:46:41Z,anger
765505392,This should probably done in common code rather than specialcasing/reinventing the wheel for known_hosts. See the copy module as an example of using preserve permissions with standard functions.,2021-01-22T15:56:40Z,anger
765509274,Please create a new PR using a branch in your fork. <! boilerplate: fork,2021-01-22T16:01:28Z,neutral
765509358,Do we want to add some documentation or content to address this?,2021-01-22T16:01:35Z,neutral
765521260,The test ansibletest sanity test docsbuild [[explain]( failed with 2 errors: docs/docsite/rst/reference_appendices/config.rst0: warning: Inline strong startstring without endstring. docs/docsite/rst/reference_appendices/config.rst0: warning: Inline strong startstring without endstring. <! job_id: 4694 <! job_id: 9b57cbb5e46d0e622f8f8dc80aaabf27 <! job_id: None [click here for bot help]( <! boilerplate: shippable_test_result,2021-01-22T16:17:33Z,fear
765556475," FTR the last commit fixes that second bug and will be absorbed into an earlier commit later. Meanwhile, hertel is working on regression tests for this case and we're trying to decide how to validate version better. The patch allows falsy version values in galaxy.yml but not in MANIFEST.json. It could be improved by actually parsing it with SemVer but I'm not sure if it's worth it.",2021-01-22T17:03:53Z,fear
765614465,"import_tasks cannot rely on host vars to control its behavior as it is a preprocessor macro that applies to playbook generically without any host context. To utilize host context, you must instead use include_tasks which is a runtime trigger that can be influenced on a per host basis. If you have further questions please stop by IRC or the mailing list: IRC: on irc.freenode.net mailing list: ",2021-01-22T18:47:20Z,neutral
765615455,"Ok, that's what I thought but I wanted to be sure it was an expected behavior. Thanks",2021-01-22T18:49:21Z,joy
765635753,"apt_key only checks that the key signature already exists, it does try ignore signatures for expired keys but there is no code that looks to see if the key itself has extra information now.",2021-01-22T19:28:29Z,neutral
765636540,The test ansibletest sanity test pep8 [[explain]( failed with 3 errors: lib/ansible/modules/apt_key.py5: E303: too many blank lines (2) lib/ansible/modules/apt_key.py161: E501: line too long (163 160 characters) lib/ansible/modules/apt_key.py161: E501: line too long (161 160 characters) <! job_id: 4720 <! job_id: 5e479646e84ec6b437c4469c8f061fea <! job_id: None [click here for bot help]( <! boilerplate: shippable_test_result,2021-01-22T19:30:11Z,fear
765637308,"Should we just I added a note that the aptkey module should not be used with newer releases and instead use get_url to put the keys in the proper place, but keep for backwards compat. Unless i hear otherwise I'm going to consider that as good enough and close this issue when merged.",2021-01-22T19:31:54Z,anger
765638139,"Considering that aptkey should not be used anymore (see ) and get_url already handles this in better ways, should we just close this issue? needs_info",2021-01-22T19:33:37Z,anger
765639327,"tried fixing in , but it seems that 'aptkey' command can return 'all fine' .. but then when we try to verify the key was added, it did not happen. I've updated info in the error message, but I'm still not sure how this happens.",2021-01-22T19:35:57Z,anger
765640959,"considering hints we should not be using aptkey anymore, is this still a concern? was thinking real fix was adding force as dumping the full keys and comparing them seems overkill. needs_info",2021-01-22T19:39:18Z,fear
765642479,Thank you for following up.,2021-01-22T19:42:03Z,joy
765657340,"It's not strictly required, but the work I am doing in would make this much easier to deal with. I wouldn't work on adding vars_files until that PR merges, or we determine that is not feasible.",2021-01-22T20:11:52Z,neutral
765662247,"The test ansibletest sanity test ansibledoc [[explain]( failed with the error: Output on stderr from ansibledoc is considered an error. Command ""ansibledoc t module apt_key"" returned exit status 0. Standard Error [WARNING]: While constructing a mapping from /root/ansible/lib/ansible/modules/apt_key.py, line 3, column 1, found a duplicate dict key (notes). Using last defined value only. <! job_id: 4725 <! job_id: f97f36e2776417147ce9d0edecea4d2c <! job_id: None The test ansibletest sanity test yamllint [[explain]( failed with 1 error: lib/ansible/modules/apt_key.py1: keyduplicates: DOCUMENTATION: duplication of key ""notes"" in mapping <! job_id: 4725 <! job_id: 95131e49cdda23ca4d893250c5f8ad3c <! job_id: None [click here for bot help]( <! boilerplate: shippable_test_result ",2021-01-22T20:22:27Z,fear
765662650," You have not responded to information requests in this issue so we will assume it no longer affects you. If you are still interested in this, please create a new issue with the requested information. [click here for bot help]( <! boilerplate: needs_info_base ",2021-01-22T20:23:15Z,anger
765681406,Thanks! :),2021-01-22T21:00:31Z,joy
766802047,Would you mind testing and let us know if it fixes the issue with your playbooks? Thanks!,2021-01-25T13:05:16Z,joy